// AUTO-GENERATED oleh scripts/gen-mock.mjs pada 2026-09-24T13:31:07.504Z
// Sumber: GitHub API (fetch langsung)
// Snapshot nyata akun GitHub — dipakai OTOMATIS saat GitHub API rate-limit
// atau saat build static export (GitHub Pages). Regenerasi: npm run gen:mock
import type { Snapshot } from './types';

export const MOCK_SNAPSHOT: Snapshot = {
  "user": {
    "login": "Niumination",
    "name": "Niumination",
    "avatar": "https://avatars.githubusercontent.com/u/123625275?v=4",
    "bio": null,
    "location": "Aceh Tengah",
    "company": null,
    "blog": "https://github.com/niumination",
    "twitter": null,
    "followers": 2,
    "following": 19,
    "publicRepos": 89,
    "joinedAt": "2023-01-26T08:06:49Z"
  },
  "repos": [
    {
      "name": "Niumination",
      "fullName": "Niumination/Niumination",
      "url": "https://github.com/Niumination/Niumination",
      "description": "Niumination GitHub Profile README — animated terminal hero. Deployed from agents/profile/.",
      "language": "JavaScript",
      "stars": 1,
      "forks": 0,
      "watchers": 1,
      "openIssues": 0,
      "topics": [
        "aceh-tengah",
        "github-profile",
        "niumination",
        "readme",
        "spbe"
      ],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 96,
      "createdAt": "2026-07-15T10:38:11Z",
      "pushedAt": "2026-09-24T13:20:49Z"
    },
    {
      "name": "Niu-OSS-Dashboard",
      "fullName": "Niumination/Niu-OSS-Dashboard",
      "url": "https://github.com/Niumination/Niu-OSS-Dashboard",
      "description": "Landing + dasbor OSS Niumination — Next.js 16, agregator 90 repo publik, API publik v1 (107 endpoint), PWA offline, i18n id/en penuh, a11y WCAG 2.2 AA",
      "language": "TypeScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://niu-oss.vercel.app",
      "fork": false,
      "archived": false,
      "license": null,
      "size": 967,
      "createdAt": "2026-09-19T09:44:20Z",
      "pushedAt": "2026-09-24T12:53:15Z"
    },
    {
      "name": "ecosystem-config",
      "fullName": "Niumination/ecosystem-config",
      "url": "https://github.com/Niumination/ecosystem-config",
      "description": "Niumination Ecosystem — orchestration/index repo: AGENTS.md, BACKLOG.md, scripts, docs. v4.0 maturity pipeline.",
      "language": "JavaScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 44939,
      "createdAt": "2026-07-16T17:39:24Z",
      "pushedAt": "2026-09-24T12:31:47Z"
    },
    {
      "name": "sapa-ai",
      "fullName": "Niumination/sapa-ai",
      "url": "https://github.com/Niumination/sapa-ai",
      "description": null,
      "language": "TypeScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://sapa-ai-indol.vercel.app",
      "fork": false,
      "archived": false,
      "license": "NOASSERTION",
      "size": 1972,
      "createdAt": "2026-09-01T17:26:26Z",
      "pushedAt": "2026-09-23T18:39:44Z"
    },
    {
      "name": "PemdiAcehTengah",
      "fullName": "Niumination/PemdiAcehTengah",
      "url": "https://github.com/Niumination/PemdiAcehTengah",
      "description": "Portal Digital Pemerintah Kabupaten Aceh Tengah — 52 perangkat daerah, peta proses bisnis (PermenPANRB 19/2018), dan evaluasi indeks Pemdi (PermenPANRB 8/2026). Next.js + Supabase, MIT.",
      "language": "JavaScript",
      "stars": 1,
      "forks": 0,
      "watchers": 1,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://pemdi-aceh-tengah.vercel.app",
      "fork": false,
      "archived": false,
      "license": "MIT",
      "size": 758177,
      "createdAt": "2026-06-03T17:41:18Z",
      "pushedAt": "2026-09-23T15:04:16Z"
    },
    {
      "name": "niu-dash",
      "fullName": "Niumination/niu-dash",
      "url": "https://github.com/Niumination/niu-dash",
      "description": "Dark web glitch dashboard — 76 projects tracked. Niumination project inventory & DEV TRACKER.",
      "language": "HTML",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 1,
      "topics": [],
      "homepage": "https://niumination.github.io/niu-dash/",
      "fork": false,
      "archived": false,
      "license": "MIT",
      "size": 1930,
      "createdAt": "2026-06-03T09:03:02Z",
      "pushedAt": "2026-09-23T07:22:12Z"
    },
    {
      "name": "niu-cast",
      "fullName": "Niumination/niu-cast",
      "url": "https://github.com/Niumination/niu-cast",
      "description": null,
      "language": "Java",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 1,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 163918,
      "createdAt": "2026-06-12T17:13:07Z",
      "pushedAt": "2026-09-19T17:08:19Z"
    },
    {
      "name": "niu-mission-control",
      "fullName": "Niumination/niu-mission-control",
      "url": "https://github.com/Niumination/niu-mission-control",
      "description": null,
      "language": "JavaScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 12139,
      "createdAt": "2026-07-16T18:33:36Z",
      "pushedAt": "2026-09-19T17:07:22Z"
    },
    {
      "name": "niu-gayo-agroclimate",
      "fullName": "Niumination/niu-gayo-agroclimate",
      "url": "https://github.com/Niumination/niu-gayo-agroclimate",
      "description": "Sistem Presisi Cuaca Pertanian Kopi Arabika Gayo & Mitigasi Bencana Aceh Tengah (WeatherNext Pipeline)",
      "language": "HTML",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 45,
      "createdAt": "2026-09-07T08:11:54Z",
      "pushedAt": "2026-09-19T17:07:18Z"
    },
    {
      "name": "SPBE-DevOps-Academy",
      "fullName": "Niumination/SPBE-DevOps-Academy",
      "url": "https://github.com/Niumination/SPBE-DevOps-Academy",
      "description": null,
      "language": "JavaScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 121,
      "createdAt": "2025-11-04T18:11:42Z",
      "pushedAt": "2026-09-18T11:14:28Z"
    },
    {
      "name": "kms-spbe",
      "fullName": "Niumination/kms-spbe",
      "url": "https://github.com/Niumination/kms-spbe",
      "description": null,
      "language": "TypeScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://kms-spbe.vercel.app",
      "fork": false,
      "archived": false,
      "license": null,
      "size": 474,
      "createdAt": "2025-10-24T19:45:35Z",
      "pushedAt": "2026-09-18T11:12:05Z"
    },
    {
      "name": "kune-ya.com",
      "fullName": "Niumination/kune-ya.com",
      "url": "https://github.com/Niumination/kune-ya.com",
      "description": null,
      "language": "TypeScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://kune-ya-com.vercel.app",
      "fork": false,
      "archived": false,
      "license": null,
      "size": 192,
      "createdAt": "2026-06-06T18:45:21Z",
      "pushedAt": "2026-09-18T11:10:41Z"
    },
    {
      "name": "mata-watchdog-pi",
      "fullName": "Niumination/mata-watchdog-pi",
      "url": "https://github.com/Niumination/mata-watchdog-pi",
      "description": "MATA Watchdog — Pi App Studio dashboard for public procurement transparency in Central Aceh",
      "language": "JavaScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 28,
      "createdAt": "2026-09-16T11:44:01Z",
      "pushedAt": "2026-09-16T16:33:41Z"
    },
    {
      "name": "mata-aihackfest-2026",
      "fullName": "Niumination/mata-aihackfest-2026",
      "url": "https://github.com/Niumination/mata-aihackfest-2026",
      "description": "MATA — Watchdog Akuntabilitas Pengadaan. AI HackFest 2026 Batch 3 (Productivity & Personal AI).",
      "language": "HTML",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://watchdog-mata.niumination.web.id",
      "fork": false,
      "archived": false,
      "license": null,
      "size": 7672,
      "createdAt": "2026-09-11T08:10:53Z",
      "pushedAt": "2026-09-16T07:34:20Z"
    },
    {
      "name": "ai-file-organizer-android",
      "fullName": "Niumination/ai-file-organizer-android",
      "url": "https://github.com/Niumination/ai-file-organizer-android",
      "description": "AI File Organizer for Android — merapikan file SD Card / internal storage pakai Google Gemini AI. Kotlin, Jetpack Compose, SAF Scoped Storage.",
      "language": "Kotlin",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 2772,
      "createdAt": "2026-06-23T06:36:58Z",
      "pushedAt": "2026-09-13T15:20:10Z"
    },
    {
      "name": "hermes-agent",
      "fullName": "Niumination/hermes-agent",
      "url": "https://github.com/Niumination/hermes-agent",
      "description": "The agent that grows with you",
      "language": "Python",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://hermes-agent.nousresearch.com",
      "fork": true,
      "archived": false,
      "license": "MIT",
      "size": 774843,
      "createdAt": "2026-08-24T17:55:30Z",
      "pushedAt": "2026-09-09T18:13:10Z"
    },
    {
      "name": "Smart-ASN-Gayo-Mengaji",
      "fullName": "Niumination/Smart-ASN-Gayo-Mengaji",
      "url": "https://github.com/Niumination/Smart-ASN-Gayo-Mengaji",
      "description": "Gayo-Mengaji",
      "language": "TypeScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 183,
      "createdAt": "2026-09-08T16:58:08Z",
      "pushedAt": "2026-09-09T06:20:54Z"
    },
    {
      "name": "Niu-LKH",
      "fullName": "Niumination/Niu-LKH",
      "url": "https://github.com/Niumination/Niu-LKH",
      "description": "Laporan Kegiatan Harian - Afrizal Munthe",
      "language": "JavaScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://niumination.github.io/Niu-LKH/",
      "fork": false,
      "archived": false,
      "license": null,
      "size": 4100,
      "createdAt": "2025-10-21T09:31:49Z",
      "pushedAt": "2026-09-07T07:17:30Z"
    },
    {
      "name": "niu-journal",
      "fullName": "Niumination/niu-journal",
      "url": "https://github.com/Niumination/niu-journal",
      "description": "Aplikasi Tahap dua - Akademi Gen AI edisi APAC",
      "language": "TypeScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 183,
      "createdAt": "2026-09-05T10:08:31Z",
      "pushedAt": "2026-09-05T10:09:48Z"
    },
    {
      "name": "niu-journal-reflection-assistant",
      "fullName": "Niumination/niu-journal-reflection-assistant",
      "url": "https://github.com/Niumination/niu-journal-reflection-assistant",
      "description": "Aplikasi Prototipe tahap awal program Akademi Gen AI APAC Edition - Cohort 3",
      "language": "TypeScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 156,
      "createdAt": "2026-09-05T08:06:40Z",
      "pushedAt": "2026-09-05T08:07:31Z"
    },
    {
      "name": "jcode-eco",
      "fullName": "Niumination/jcode-eco",
      "url": "https://github.com/Niumination/jcode-eco",
      "description": "Jcode Ecosystem - AI Agent workspace",
      "language": "Python",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 312,
      "createdAt": "2026-08-30T08:38:08Z",
      "pushedAt": "2026-08-30T08:44:41Z"
    },
    {
      "name": "Flame-ADE",
      "fullName": "Niumination/Flame-ADE",
      "url": "https://github.com/Niumination/Flame-ADE",
      "description": "~7MB AI-native terminal emulator (ADE) — Tauri 2 + Rust + React 19. macOS Tahoe 26.5 primary target. BYOK AI, no telemetry, OS keychain.",
      "language": "TypeScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 1,
      "topics": [
        "ade",
        "ai",
        "ai-agent",
        "byok",
        "codemirror",
        "hackintosh",
        "macos",
        "opensource",
        "portable-pty",
        "react",
        "rust",
        "tailwindcss",
        "tauri",
        "tauri-app",
        "terminal",
        "terminal-emulator",
        "typescript",
        "vite",
        "xterm",
        "zustand"
      ],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": "Apache-2.0",
      "size": 703,
      "createdAt": "2026-05-23T00:11:54Z",
      "pushedAt": "2026-08-28T10:23:37Z"
    },
    {
      "name": "pabrik-aplikasi-gas",
      "fullName": "Niumination/pabrik-aplikasi-gas",
      "url": "https://github.com/Niumination/pabrik-aplikasi-gas",
      "description": "Pabrik Aplikasi - Inventaris Aset TI (GAS pilot project)",
      "language": "JavaScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 122,
      "createdAt": "2026-08-26T12:19:48Z",
      "pushedAt": "2026-08-26T18:44:19Z"
    },
    {
      "name": "APEX-UI",
      "fullName": "Niumination/APEX-UI",
      "url": "https://github.com/Niumination/APEX-UI",
      "description": "The front interface of the AI assistant APEX by Reznikov Engineering ",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://apex-ui-xi.vercel.app",
      "fork": true,
      "archived": false,
      "license": "MIT",
      "size": 107,
      "createdAt": "2026-08-20T14:04:21Z",
      "pushedAt": "2026-08-20T10:22:24Z"
    },
    {
      "name": "pdf-inspector",
      "fullName": "Niumination/pdf-inspector",
      "url": "https://github.com/Niumination/pdf-inspector",
      "description": "Inspeksi PDF lokal tanpa LLM (no-agent) — pypdf. Baca isi PDF ke teks/ringkasan untuk agen.",
      "language": "Python",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 2,
      "createdAt": "2026-08-20T04:30:28Z",
      "pushedAt": "2026-08-20T04:30:40Z"
    },
    {
      "name": "spatial-vision",
      "fullName": "Niumination/spatial-vision",
      "url": "https://github.com/Niumination/spatial-vision",
      "description": "Full-stack Rust/WASM spatial UI — Axum backend + wasm-bindgen frontend, gesture/pinch detection, WebSocket broadcast",
      "language": "HTML",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 19789,
      "createdAt": "2026-07-22T06:25:04Z",
      "pushedAt": "2026-08-18T12:26:03Z"
    },
    {
      "name": "UACC",
      "fullName": "Niumination/UACC",
      "url": "https://github.com/Niumination/UACC",
      "description": null,
      "language": "Python",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": true,
      "archived": false,
      "license": "MIT",
      "size": 3319,
      "createdAt": "2026-07-27T09:47:22Z",
      "pushedAt": "2026-08-18T12:25:35Z"
    },
    {
      "name": "mac-web-dashboard",
      "fullName": "Niumination/mac-web-dashboard",
      "url": "https://github.com/Niumination/mac-web-dashboard",
      "description": null,
      "language": "TypeScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 117,
      "createdAt": "2026-06-21T16:01:17Z",
      "pushedAt": "2026-08-18T12:25:18Z"
    },
    {
      "name": "arch-web-dashboard",
      "fullName": "Niumination/arch-web-dashboard",
      "url": "https://github.com/Niumination/arch-web-dashboard",
      "description": null,
      "language": "TypeScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 34,
      "createdAt": "2026-06-21T15:44:00Z",
      "pushedAt": "2026-08-18T12:25:15Z"
    },
    {
      "name": "latticesend",
      "fullName": "Niumination/latticesend",
      "url": "https://github.com/Niumination/latticesend",
      "description": "P2P file transfer tool — built with Rust/Flutter. Part of Niumination Ecosystem services.",
      "language": "HTML",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": "MIT",
      "size": 214,
      "createdAt": "2026-07-28T17:08:23Z",
      "pushedAt": "2026-08-10T09:11:59Z"
    },
    {
      "name": "cc-switch",
      "fullName": "Niumination/cc-switch",
      "url": "https://github.com/Niumination/cc-switch",
      "description": "A cross-platform desktop All-in-One assistant for Claude Code, Codex, OpenCode, OpenClaw, Gemini CLI & Hermes Agent. Only official website: ccswitch.io",
      "language": "Rust",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://ccswitch.io",
      "fork": true,
      "archived": false,
      "license": "MIT",
      "size": 66120,
      "createdAt": "2026-07-19T17:46:39Z",
      "pushedAt": "2026-08-07T20:36:46Z"
    },
    {
      "name": "Android-Dex",
      "fullName": "Niumination/Android-Dex",
      "url": "https://github.com/Niumination/Android-Dex",
      "description": "Enable a full desktop experience from any Android device over Wi‑Fi. No root, scrcpy-powered, Flutter desktop app with wireless ADB, per‑app audio, and quick controls.",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://shrey113.github.io/Android-Dex/",
      "fork": true,
      "archived": false,
      "license": null,
      "size": 141776,
      "createdAt": "2026-08-05T08:41:42Z",
      "pushedAt": "2026-08-04T19:21:44Z"
    },
    {
      "name": "niu-dash-fullstack",
      "fullName": "Niumination/niu-dash-fullstack",
      "url": "https://github.com/Niumination/niu-dash-fullstack",
      "description": "Next.js 16 Fullstack Dashboard — Prisma, Three.js, TanStack Query, next-auth",
      "language": "TypeScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 317,
      "createdAt": "2026-07-06T03:03:22Z",
      "pushedAt": "2026-07-30T09:05:41Z"
    },
    {
      "name": "airi",
      "fullName": "Niumination/airi",
      "url": "https://github.com/Niumination/airi",
      "description": "💖🧸 Self hosted, you-owned Grok Companion, a container of souls of waifu, cyber livings to bring them into our worlds, wishing to achieve Neuro-sama's altitude. Capable of realtime voice chat, Minecraft, Factorio playing. Web / macOS / Windows supported.",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://airi.moeru.ai/docs/",
      "fork": true,
      "archived": false,
      "license": "MIT",
      "size": 519728,
      "createdAt": "2026-07-27T12:22:30Z",
      "pushedAt": "2026-07-27T11:50:02Z"
    },
    {
      "name": "agentic-awesome-skills",
      "fullName": "Niumination/agentic-awesome-skills",
      "url": "https://github.com/Niumination/agentic-awesome-skills",
      "description": "AAS Core is the local, agent-first control plane for complete catalog discovery, agent-owned selection, stack validation, and planning, backed by 1,987+ agentic skills. Includes CLI, local MCP, catalog, plugins, and Workbench.",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://sickn33.github.io/agentic-awesome-skills/",
      "fork": true,
      "archived": false,
      "license": "MIT",
      "size": 111656,
      "createdAt": "2026-07-27T10:02:51Z",
      "pushedAt": "2026-07-27T05:13:52Z"
    },
    {
      "name": "opendataloader-pdf",
      "fullName": "Niumination/opendataloader-pdf",
      "url": "https://github.com/Niumination/opendataloader-pdf",
      "description": "PDF Parser for AI-ready data. Automate PDF accessibility. Open-source.",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://opendataloader.org",
      "fork": true,
      "archived": false,
      "license": "Apache-2.0",
      "size": 87651,
      "createdAt": "2026-07-27T09:55:52Z",
      "pushedAt": "2026-07-27T00:17:13Z"
    },
    {
      "name": "opencode",
      "fullName": "Niumination/opencode",
      "url": "https://github.com/Niumination/opencode",
      "description": "The open source coding agent.",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://opencode.ai",
      "fork": true,
      "archived": false,
      "license": "MIT",
      "size": 414981,
      "createdAt": "2026-07-18T11:02:44Z",
      "pushedAt": "2026-07-18T07:38:02Z"
    },
    {
      "name": "didong-code",
      "fullName": "Niumination/didong-code",
      "url": "https://github.com/Niumination/didong-code",
      "description": "Didong-Code — Agentic Development Environment dengan jiwa tradisi Gayo Aceh. Electron + React + TypeScript AI coding agent desktop.",
      "language": "TypeScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://github.com/Niumination/didong-code",
      "fork": false,
      "archived": false,
      "license": "MIT",
      "size": 130,
      "createdAt": "2026-07-07T17:02:32Z",
      "pushedAt": "2026-07-07T17:58:50Z"
    },
    {
      "name": "AI-First-OS",
      "fullName": "Niumination/AI-First-OS",
      "url": "https://github.com/Niumination/AI-First-OS",
      "description": "Arch Linux ISO builder — AI First OS. Sistem operasi dengan Hermes Agent sebagai warga negara kelas satu.",
      "language": "Shell",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 5,
      "createdAt": "2026-06-21T17:44:50Z",
      "pushedAt": "2026-06-27T07:39:47Z"
    },
    {
      "name": "Maze-3D-Game---Web-Based",
      "fullName": "Niumination/Maze-3D-Game---Web-Based",
      "url": "https://github.com/Niumination/Maze-3D-Game---Web-Based",
      "description": null,
      "language": "HTML",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 27,
      "createdAt": "2026-05-20T08:50:45Z",
      "pushedAt": "2026-06-27T07:38:33Z"
    },
    {
      "name": "HermesV-Github",
      "fullName": "Niumination/HermesV-Github",
      "url": "https://github.com/Niumination/HermesV-Github",
      "description": "Hermes Agent Portable on Github Codespace",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 8,
      "createdAt": "2026-06-06T04:09:05Z",
      "pushedAt": "2026-06-11T10:53:20Z"
    },
    {
      "name": "niu-private",
      "fullName": "Niumination/niu-private",
      "url": "https://github.com/Niumination/niu-private",
      "description": "Niu Private — Document Vault & Kanban Project Board",
      "language": "TypeScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://niumination.github.io/niu-private/",
      "fork": false,
      "archived": false,
      "license": null,
      "size": 130,
      "createdAt": "2026-06-06T06:52:57Z",
      "pushedAt": "2026-06-08T05:25:27Z"
    },
    {
      "name": "VirtualAssistance",
      "fullName": "Niumination/VirtualAssistance",
      "url": "https://github.com/Niumination/VirtualAssistance",
      "description": null,
      "language": "TypeScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://virtual-assistance-pi.vercel.app",
      "fork": false,
      "archived": false,
      "license": null,
      "size": 113,
      "createdAt": "2026-06-03T15:44:28Z",
      "pushedAt": "2026-06-03T16:51:00Z"
    },
    {
      "name": "flame-code",
      "fullName": "Niumination/flame-code",
      "url": "https://github.com/Niumination/flame-code",
      "description": "My First Build, Using AI",
      "language": "TypeScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 1541,
      "createdAt": "2026-05-31T17:17:37Z",
      "pushedAt": "2026-05-31T17:22:02Z"
    },
    {
      "name": "terax-ai",
      "fullName": "Niumination/terax-ai",
      "url": "https://github.com/Niumination/terax-ai",
      "description": "Lightweight (7MB) AI terminal emulator (ADE) built in Rust & Tauri & React",
      "language": "TypeScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://terax.app",
      "fork": true,
      "archived": false,
      "license": "Apache-2.0",
      "size": 12345,
      "createdAt": "2026-05-20T07:36:30Z",
      "pushedAt": "2026-05-31T07:20:40Z"
    },
    {
      "name": "free-vps",
      "fullName": "Niumination/free-vps",
      "url": "https://github.com/Niumination/free-vps",
      "description": null,
      "language": "TypeScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 278,
      "createdAt": "2026-05-29T07:45:29Z",
      "pushedAt": "2026-05-29T09:47:11Z"
    },
    {
      "name": "jcode",
      "fullName": "Niumination/jcode",
      "url": "https://github.com/Niumination/jcode",
      "description": "Coding Agent Harness",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "",
      "fork": true,
      "archived": false,
      "license": "MIT",
      "size": 381348,
      "createdAt": "2026-05-17T14:19:36Z",
      "pushedAt": "2026-05-17T03:36:04Z"
    },
    {
      "name": "skills",
      "fullName": "Niumination/skills",
      "url": "https://github.com/Niumination/skills",
      "description": "Skills for Real Engineers. Straight from my .claude directory.",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "",
      "fork": true,
      "archived": false,
      "license": "MIT",
      "size": 200,
      "createdAt": "2026-05-18T11:53:28Z",
      "pushedAt": "2026-05-13T13:05:22Z"
    },
    {
      "name": "Free-Claude-Opus",
      "fullName": "Niumination/Free-Claude-Opus",
      "url": "https://github.com/Niumination/Free-Claude-Opus",
      "description": null,
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": true,
      "archived": false,
      "license": null,
      "size": 9,
      "createdAt": "2026-04-26T12:09:09Z",
      "pushedAt": "2026-04-23T06:55:10Z"
    },
    {
      "name": "G0DM0D3",
      "fullName": "Niumination/G0DM0D3",
      "url": "https://github.com/Niumination/G0DM0D3",
      "description": "LIBERATED AI CHAT",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": true,
      "archived": false,
      "license": "AGPL-3.0",
      "size": 1078,
      "createdAt": "2026-05-25T04:16:03Z",
      "pushedAt": "2026-03-26T02:55:07Z"
    },
    {
      "name": "disunday",
      "fullName": "Niumination/disunday",
      "url": "https://github.com/Niumination/disunday",
      "description": "Control opencode from Discord. Say goodbye to Sundays—manage your AI coding projects 24/7 through Discord channels.",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "",
      "fork": true,
      "archived": false,
      "license": "MIT",
      "size": 1978,
      "createdAt": "2026-05-29T01:44:06Z",
      "pushedAt": "2026-02-23T09:31:42Z"
    },
    {
      "name": "Bella",
      "fullName": "Niumination/Bella",
      "url": "https://github.com/Niumination/Bella",
      "description": "Bella is best",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "",
      "fork": true,
      "archived": false,
      "license": null,
      "size": 107636,
      "createdAt": "2026-05-24T18:11:08Z",
      "pushedAt": "2026-02-05T02:58:42Z"
    },
    {
      "name": "roboto_origin",
      "fullName": "Niumination/roboto_origin",
      "url": "https://github.com/Niumination/roboto_origin",
      "description": "Roboto_origin Fully Open-Source DIY Humanoid Robot/萝博头原型机全开源手搓级人形机器人",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "",
      "fork": true,
      "archived": false,
      "license": null,
      "size": 754527,
      "createdAt": "2026-02-11T02:34:23Z",
      "pushedAt": "2026-02-04T10:55:40Z"
    },
    {
      "name": "lmarena.github.io",
      "fullName": "Niumination/lmarena.github.io",
      "url": "https://github.com/Niumination/lmarena.github.io",
      "description": null,
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": true,
      "archived": false,
      "license": "MIT",
      "size": 320259,
      "createdAt": "2026-05-25T17:22:05Z",
      "pushedAt": "2026-01-04T04:50:19Z"
    },
    {
      "name": "ryu-dots",
      "fullName": "Niumination/ryu-dots",
      "url": "https://github.com/Niumination/ryu-dots",
      "description": "Complete Arch Linux system configuration with Hyprland + Illogical Impulse",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 0,
      "createdAt": "2025-11-17T04:34:00Z",
      "pushedAt": "2025-11-17T04:34:00Z"
    },
    {
      "name": "niu-speedtest",
      "fullName": "Niumination/niu-speedtest",
      "url": "https://github.com/Niumination/niu-speedtest",
      "description": null,
      "language": "Python",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": "MIT",
      "size": 13,
      "createdAt": "2025-11-15T02:27:59Z",
      "pushedAt": "2025-11-16T02:21:00Z"
    },
    {
      "name": "Devs-Niu",
      "fullName": "Niumination/Devs-Niu",
      "url": "https://github.com/Niumination/Devs-Niu",
      "description": null,
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 0,
      "createdAt": "2025-11-08T06:58:00Z",
      "pushedAt": "2025-11-08T06:58:00Z"
    },
    {
      "name": "Continue-Agent",
      "fullName": "Niumination/Continue-Agent",
      "url": "https://github.com/Niumination/Continue-Agent",
      "description": null,
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 0,
      "createdAt": "2025-10-26T17:07:37Z",
      "pushedAt": "2025-10-26T17:10:25Z"
    },
    {
      "name": "SilentSDDM",
      "fullName": "Niumination/SilentSDDM",
      "url": "https://github.com/Niumination/SilentSDDM",
      "description": "A very customizable SDDM theme that actually looks good.",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "",
      "fork": true,
      "archived": false,
      "license": "GPL-3.0",
      "size": 230669,
      "createdAt": "2025-10-26T07:49:14Z",
      "pushedAt": "2025-10-23T14:13:52Z"
    },
    {
      "name": "Niu-Startpage",
      "fullName": "Niumination/Niu-Startpage",
      "url": "https://github.com/Niumination/Niu-Startpage",
      "description": "My Gateway to the internet",
      "language": "HTML",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://niumination.github.io/Niu-Startpage/",
      "fork": false,
      "archived": false,
      "license": null,
      "size": 156,
      "createdAt": "2025-10-20T06:59:34Z",
      "pushedAt": "2025-10-22T09:27:33Z"
    },
    {
      "name": "Niu-Cyber-Search-Engine",
      "fullName": "Niumination/Niu-Cyber-Search-Engine",
      "url": "https://github.com/Niumination/Niu-Cyber-Search-Engine",
      "description": "My First Cyber Search Engine App",
      "language": "TypeScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://niu-cyber.vercel.app",
      "fork": false,
      "archived": false,
      "license": null,
      "size": 236,
      "createdAt": "2025-10-22T03:04:33Z",
      "pushedAt": "2025-10-22T04:03:39Z"
    },
    {
      "name": "zaryu.startpage",
      "fullName": "Niumination/zaryu.startpage",
      "url": "https://github.com/Niumination/zaryu.startpage",
      "description": "🐱✨ Aesthetic and clean startpage in Catppuccin style, hosted on GitHub Pages",
      "language": "JavaScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://niumination.github.io/zaryu.startpage/",
      "fork": true,
      "archived": false,
      "license": "MIT",
      "size": 65907,
      "createdAt": "2024-12-07T05:01:56Z",
      "pushedAt": "2025-10-13T14:47:27Z"
    },
    {
      "name": "NiuHomePage",
      "fullName": "Niumination/NiuHomePage",
      "url": "https://github.com/Niumination/NiuHomePage",
      "description": "I wanted a home page, so I made one.",
      "language": "CSS",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://niumination.github.io/NiuHomePage/",
      "fork": true,
      "archived": false,
      "license": "MIT",
      "size": 16593,
      "createdAt": "2025-09-18T15:05:52Z",
      "pushedAt": "2025-10-13T13:00:51Z"
    },
    {
      "name": "PAGASUS-PRO",
      "fullName": "Niumination/PAGASUS-PRO",
      "url": "https://github.com/Niumination/PAGASUS-PRO",
      "description": null,
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": true,
      "archived": false,
      "license": "NOASSERTION",
      "size": 220,
      "createdAt": "2025-10-07T14:06:51Z",
      "pushedAt": "2025-10-03T13:50:38Z"
    },
    {
      "name": "mcp-for-beginners-Microsoft",
      "fullName": "Niumination/mcp-for-beginners-Microsoft",
      "url": "https://github.com/Niumination/mcp-for-beginners-Microsoft",
      "description": "This open-source curriculum introduces the fundamentals of Model Context Protocol (MCP) through real-world, cross-language examples in .NET, Java, TypeScript, JavaScript, Rust and Python. Designed for developers, it focuses on practical techniques for building modular, scalable, and secure AI workflows from session setup to service orchestration.",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "",
      "fork": true,
      "archived": false,
      "license": "MIT",
      "size": 2168552,
      "createdAt": "2025-10-04T16:07:00Z",
      "pushedAt": "2025-10-03T08:42:01Z"
    },
    {
      "name": "ryuland-dotfiles",
      "fullName": "Niumination/ryuland-dotfiles",
      "url": "https://github.com/Niumination/ryuland-dotfiles",
      "description": "Rice built for usability",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://end-4.github.io/dots-hyprland-wiki/en/",
      "fork": true,
      "archived": false,
      "license": "GPL-3.0",
      "size": 19628,
      "createdAt": "2025-09-29T11:02:27Z",
      "pushedAt": "2025-09-29T08:28:56Z"
    },
    {
      "name": "Prakom-Surgawi",
      "fullName": "Niumination/Prakom-Surgawi",
      "url": "https://github.com/Niumination/Prakom-Surgawi",
      "description": "Anything you want",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 0,
      "createdAt": "2025-09-26T12:23:33Z",
      "pushedAt": "2025-09-26T12:23:34Z"
    },
    {
      "name": "cursor-free-vip",
      "fullName": "Niumination/cursor-free-vip",
      "url": "https://github.com/Niumination/cursor-free-vip",
      "description": "[Support 0.49.x]（Reset Cursor AI MachineID & Bypass Higher Token Limit） Cursor Ai ，自动重置机器ID ， 免费升级使用Pro功能: You've reached your trial request limit. / Too many free trial accounts used on this machine. Please upgrade to pro. We have this limit in place to prevent abuse. Please let us know if you believe this is a mistake.",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://www.cursor.com/",
      "fork": true,
      "archived": false,
      "license": "NOASSERTION",
      "size": 12241,
      "createdAt": "2025-10-27T01:54:22Z",
      "pushedAt": "2025-09-16T03:47:39Z"
    },
    {
      "name": "docker-mcp-tutorial",
      "fullName": "Niumination/docker-mcp-tutorial",
      "url": "https://github.com/Niumination/docker-mcp-tutorial",
      "description": "Complete tutorial materials for building MCP servers with Docker - from NetworkChuck's video",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": true,
      "archived": false,
      "license": "MIT",
      "size": 35,
      "createdAt": "2025-10-07T10:15:42Z",
      "pushedAt": "2025-09-12T15:21:49Z"
    },
    {
      "name": "hyprfloat",
      "fullName": "Niumination/hyprfloat",
      "url": "https://github.com/Niumination/hyprfloat",
      "description": "Hyprland floating window manager and workspace overview utility.",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": true,
      "archived": false,
      "license": "MIT",
      "size": 15165,
      "createdAt": "2025-09-11T08:18:35Z",
      "pushedAt": "2025-09-11T07:10:07Z"
    },
    {
      "name": "ryushell",
      "fullName": "Niumination/ryushell",
      "url": "https://github.com/Niumination/ryushell",
      "description": "‼️ No waybar here ‼️",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "",
      "fork": true,
      "archived": false,
      "license": "GPL-3.0",
      "size": 1869,
      "createdAt": "2025-09-10T15:13:58Z",
      "pushedAt": "2025-09-10T12:57:16Z"
    },
    {
      "name": "Windots",
      "fullName": "Niumination/Windots",
      "url": "https://github.com/Niumination/Windots",
      "description": "A collection of my personal Windows dotfiles and configs.",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "",
      "fork": true,
      "archived": false,
      "license": "MIT",
      "size": 73283,
      "createdAt": "2025-07-02T09:02:09Z",
      "pushedAt": "2025-08-04T05:04:36Z"
    },
    {
      "name": "unlimited-claude-AI",
      "fullName": "Niumination/unlimited-claude-AI",
      "url": "https://github.com/Niumination/unlimited-claude-AI",
      "description": "Claude AI. No backend, no server costs, 100% free.",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "",
      "fork": true,
      "archived": false,
      "license": "MIT",
      "size": 669,
      "createdAt": "2026-04-20T17:21:04Z",
      "pushedAt": "2025-07-22T06:01:32Z"
    },
    {
      "name": "ryuland",
      "fullName": "Niumination/ryuland",
      "url": "https://github.com/Niumination/ryuland",
      "description": "Unleash the power of Hyprland with our modern, useful, user friendly, islamic halal Hyprland ecosystem dots",
      "language": "JavaScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://hyprluna.org",
      "fork": true,
      "archived": false,
      "license": "MIT",
      "size": 203755,
      "createdAt": "2025-06-12T04:13:23Z",
      "pushedAt": "2025-07-22T05:11:03Z"
    },
    {
      "name": "cyb3rgh0u1.github.io",
      "fullName": "Niumination/cyb3rgh0u1.github.io",
      "url": "https://github.com/Niumination/cyb3rgh0u1.github.io",
      "description": null,
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://cyb3rgh0u1.github.io/",
      "fork": true,
      "archived": false,
      "license": "MIT",
      "size": 975,
      "createdAt": "2025-07-04T10:40:26Z",
      "pushedAt": "2025-07-01T22:30:24Z"
    },
    {
      "name": "Zaryu-HyDE",
      "fullName": "Niumination/Zaryu-HyDE",
      "url": "https://github.com/Niumination/Zaryu-HyDE",
      "description": "Portable and extensible  re-work  of prasanthrangan/hyprdots // Aesthetic, dynamic and minimal dots for Arch  Hyprland // Going beyond ",
      "language": "Shell",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "",
      "fork": true,
      "archived": false,
      "license": "GPL-3.0",
      "size": 1302316,
      "createdAt": "2024-12-02T09:14:56Z",
      "pushedAt": "2025-06-17T02:56:55Z"
    },
    {
      "name": "RyuDE",
      "fullName": "Niumination/RyuDE",
      "url": "https://github.com/Niumination/RyuDE",
      "description": "My Personal Desktop Environtment Based On HyDE-Project",
      "language": "C++",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 151241,
      "createdAt": "2025-05-26T14:36:55Z",
      "pushedAt": "2025-05-28T11:00:08Z"
    },
    {
      "name": "ZaryuHive",
      "fullName": "Niumination/ZaryuHive",
      "url": "https://github.com/Niumination/ZaryuHive",
      "description": null,
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 79847,
      "createdAt": "2024-12-05T05:00:59Z",
      "pushedAt": "2025-05-27T02:58:20Z"
    },
    {
      "name": "win11-dotfiles",
      "fullName": "Niumination/win11-dotfiles",
      "url": "https://github.com/Niumination/win11-dotfiles",
      "description": "my current desktop dotfiles",
      "language": "CSS",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": true,
      "archived": false,
      "license": null,
      "size": 88289,
      "createdAt": "2025-02-20T08:25:29Z",
      "pushedAt": "2025-05-06T04:11:02Z"
    },
    {
      "name": "hyprnix",
      "fullName": "Niumination/hyprnix",
      "url": "https://github.com/Niumination/hyprnix",
      "description": null,
      "language": "Nix",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 784,
      "createdAt": "2024-11-13T11:11:11Z",
      "pushedAt": "2025-02-24T06:30:53Z"
    },
    {
      "name": "hyprdots",
      "fullName": "Niumination/hyprdots",
      "url": "https://github.com/Niumination/hyprdots",
      "description": "// Aesthetic, dynamic and minimal dots for Arch hyprland",
      "language": "Shell",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "",
      "fork": true,
      "archived": false,
      "license": "GPL-3.0",
      "size": 973984,
      "createdAt": "2024-12-04T03:49:52Z",
      "pushedAt": "2025-02-13T07:15:15Z"
    },
    {
      "name": "Axenide-Dotfiles",
      "fullName": "Niumination/Axenide-Dotfiles",
      "url": "https://github.com/Niumination/Axenide-Dotfiles",
      "description": ".'s",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "",
      "fork": true,
      "archived": false,
      "license": null,
      "size": 451494,
      "createdAt": "2025-01-18T15:32:02Z",
      "pushedAt": "2025-01-17T00:31:13Z"
    },
    {
      "name": "agsv1-hyprpanel",
      "fullName": "Niumination/agsv1-hyprpanel",
      "url": "https://github.com/Niumination/agsv1-hyprpanel",
      "description": "for use agsv1",
      "language": "TypeScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": "MIT",
      "size": 10122,
      "createdAt": "2025-01-09T11:35:51Z",
      "pushedAt": "2025-01-09T11:36:03Z"
    },
    {
      "name": "hive-dotfiles",
      "fullName": "Niumination/hive-dotfiles",
      "url": "https://github.com/Niumination/hive-dotfiles",
      "description": null,
      "language": "CSS",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 136843,
      "createdAt": "2024-12-03T03:36:08Z",
      "pushedAt": "2025-01-08T08:00:56Z"
    },
    {
      "name": "kaizen",
      "fullName": "Niumination/kaizen",
      "url": "https://github.com/Niumination/kaizen",
      "description": "productive desktop environment setup.",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "",
      "fork": true,
      "archived": false,
      "license": "MIT",
      "size": 114614,
      "createdAt": "2024-12-07T15:15:21Z",
      "pushedAt": "2024-12-07T10:13:17Z"
    },
    {
      "name": "AnachonisticHypr",
      "fullName": "Niumination/AnachonisticHypr",
      "url": "https://github.com/Niumination/AnachonisticHypr",
      "description": null,
      "language": "Shell",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 137556,
      "createdAt": "2024-11-26T15:15:39Z",
      "pushedAt": "2024-11-29T12:28:44Z"
    },
    {
      "name": "matt-dotfiles",
      "fullName": "Niumination/matt-dotfiles",
      "url": "https://github.com/Niumination/matt-dotfiles",
      "description": "💄 Yet another Aesthetic Hyprland Config",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://dotfiles-docs.vercel.app/",
      "fork": true,
      "archived": false,
      "license": "GPL-3.0",
      "size": 322770,
      "createdAt": "2024-12-03T06:51:25Z",
      "pushedAt": "2024-11-28T10:25:41Z"
    },
    {
      "name": "Hyde-cli",
      "fullName": "Niumination/Hyde-cli",
      "url": "https://github.com/Niumination/Hyde-cli",
      "description": "A HyDE CLI, wrapper, tweaks , workarounds, and more!",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://github.com/prasanthrangan/hyprdots",
      "fork": true,
      "archived": false,
      "license": "GPL-3.0",
      "size": 15268,
      "createdAt": "2024-11-05T03:44:51Z",
      "pushedAt": "2024-10-31T15:20:19Z"
    },
    {
      "name": "Activate-Office-365-on-Windows-10-11",
      "fullName": "Niumination/Activate-Office-365-on-Windows-10-11",
      "url": "https://github.com/Niumination/Activate-Office-365-on-Windows-10-11",
      "description": "Leverage the cloud when you Download Microsoft 365 (Office 365). Microsoft 365 has the tools you need to seamlessly create, collaborate, and share from all your devices. And with security features such as encrypted email and data loss prevention, you and your team can work safely from anywhere.",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://www.microsoft.com/en-us/microsoft-365/download-office",
      "fork": true,
      "archived": false,
      "license": null,
      "size": 3538,
      "createdAt": "2026-04-24T08:01:54Z",
      "pushedAt": "2024-08-27T07:55:22Z"
    }
  ],
  "events": [
    {
      "id": "22043835892",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-24T12:31:48Z",
      "summary": "0 commit"
    },
    {
      "id": "15672721660",
      "type": "WatchEvent",
      "repo": "NandhaKishorM/laya",
      "repoUrl": "https://api.github.com/repos/NandhaKishorM/laya",
      "createdAt": "2026-09-24T13:26:57Z",
      "summary": "dipantau (watch)"
    },
    {
      "id": "15672674111",
      "type": "WatchEvent",
      "repo": "mizorewww/laya-mlx",
      "repoUrl": "https://api.github.com/repos/mizorewww/laya-mlx",
      "createdAt": "2026-09-24T13:26:21Z",
      "summary": "dipantau (watch)"
    },
    {
      "id": "15672642855",
      "type": "WatchEvent",
      "repo": "ipenywis/laya-ultrafast",
      "repoUrl": "https://api.github.com/repos/ipenywis/laya-ultrafast",
      "createdAt": "2026-09-24T13:25:57Z",
      "summary": "dipantau (watch)"
    },
    {
      "id": "22041527143",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-24T12:00:57Z",
      "summary": "0 commit"
    },
    {
      "id": "22038060857",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-24T12:06:20Z",
      "summary": "0 commit"
    },
    {
      "id": "21988500951",
      "type": "CreateEvent",
      "repo": "Niumination/sapa-ai",
      "repoUrl": "https://api.github.com/repos/Niumination/sapa-ai",
      "createdAt": "2026-09-23T18:39:45Z",
      "summary": "membuat branch “dev”"
    },
    {
      "id": "21982050599",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-23T18:59:07Z",
      "summary": "0 commit"
    },
    {
      "id": "21969332873",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-23T15:11:55Z",
      "summary": "0 commit"
    },
    {
      "id": "21967131806",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-23T18:05:43Z",
      "summary": "0 commit"
    },
    {
      "id": "21965859316",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-23T15:44:58Z",
      "summary": "0 commit"
    },
    {
      "id": "21965114326",
      "type": "PushEvent",
      "repo": "Niumination/Niu-OSS-Dashboard",
      "repoUrl": "https://api.github.com/repos/Niumination/Niu-OSS-Dashboard",
      "createdAt": "2026-09-23T15:38:01Z",
      "summary": "0 commit"
    },
    {
      "id": "21964057981",
      "type": "PushEvent",
      "repo": "Niumination/Niu-OSS-Dashboard",
      "repoUrl": "https://api.github.com/repos/Niumination/Niu-OSS-Dashboard",
      "createdAt": "2026-09-23T15:06:27Z",
      "summary": "0 commit"
    },
    {
      "id": "21963755455",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-23T17:19:34Z",
      "summary": "0 commit"
    },
    {
      "id": "21959386189",
      "type": "PushEvent",
      "repo": "Niumination/PemdiAcehTengah",
      "repoUrl": "https://api.github.com/repos/Niumination/PemdiAcehTengah",
      "createdAt": "2026-09-23T15:04:16Z",
      "summary": "0 commit"
    },
    {
      "id": "21957615811",
      "type": "PushEvent",
      "repo": "Niumination/Niu-OSS-Dashboard",
      "repoUrl": "https://api.github.com/repos/Niumination/Niu-OSS-Dashboard",
      "createdAt": "2026-09-23T15:59:02Z",
      "summary": "0 commit"
    },
    {
      "id": "21955226643",
      "type": "PushEvent",
      "repo": "Niumination/Niu-OSS-Dashboard",
      "repoUrl": "https://api.github.com/repos/Niumination/Niu-OSS-Dashboard",
      "createdAt": "2026-09-23T15:28:26Z",
      "summary": "0 commit"
    },
    {
      "id": "21952474210",
      "type": "PushEvent",
      "repo": "Niumination/PemdiAcehTengah",
      "repoUrl": "https://api.github.com/repos/Niumination/PemdiAcehTengah",
      "createdAt": "2026-09-23T14:53:14Z",
      "summary": "0 commit"
    },
    {
      "id": "21952123821",
      "type": "PushEvent",
      "repo": "Niumination/PemdiAcehTengah",
      "repoUrl": "https://api.github.com/repos/Niumination/PemdiAcehTengah",
      "createdAt": "2026-09-23T14:48:51Z",
      "summary": "0 commit"
    },
    {
      "id": "21927441061",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-23T07:51:13Z",
      "summary": "0 commit"
    },
    {
      "id": "21923416456",
      "type": "PushEvent",
      "repo": "Niumination/niu-dash",
      "repoUrl": "https://api.github.com/repos/Niumination/niu-dash",
      "createdAt": "2026-09-23T07:22:13Z",
      "summary": "0 commit"
    },
    {
      "id": "21918460494",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-23T07:23:52Z",
      "summary": "0 commit"
    },
    {
      "id": "21918244630",
      "type": "PushEvent",
      "repo": "Niumination/PemdiAcehTengah",
      "repoUrl": "https://api.github.com/repos/Niumination/PemdiAcehTengah",
      "createdAt": "2026-09-23T03:54:01Z",
      "summary": "0 commit"
    },
    {
      "id": "21909578988",
      "type": "PushEvent",
      "repo": "Niumination/PemdiAcehTengah",
      "repoUrl": "https://api.github.com/repos/Niumination/PemdiAcehTengah",
      "createdAt": "2026-09-23T05:10:26Z",
      "summary": "0 commit"
    },
    {
      "id": "21908869119",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-23T04:23:52Z",
      "summary": "0 commit"
    },
    {
      "id": "21905811726",
      "type": "PushEvent",
      "repo": "Niumination/Niu-OSS-Dashboard",
      "repoUrl": "https://api.github.com/repos/Niumination/Niu-OSS-Dashboard",
      "createdAt": "2026-09-23T04:11:51Z",
      "summary": "0 commit"
    },
    {
      "id": "21893969659",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-22T17:10:48Z",
      "summary": "0 commit"
    },
    {
      "id": "21878080488",
      "type": "PushEvent",
      "repo": "Niumination/PemdiAcehTengah",
      "repoUrl": "https://api.github.com/repos/Niumination/PemdiAcehTengah",
      "createdAt": "2026-09-22T16:12:04Z",
      "summary": "0 commit"
    },
    {
      "id": "21872934948",
      "type": "PushEvent",
      "repo": "Niumination/PemdiAcehTengah",
      "repoUrl": "https://api.github.com/repos/Niumination/PemdiAcehTengah",
      "createdAt": "2026-09-22T17:57:35Z",
      "summary": "0 commit"
    },
    {
      "id": "21872021136",
      "type": "PushEvent",
      "repo": "Niumination/PemdiAcehTengah",
      "repoUrl": "https://api.github.com/repos/Niumination/PemdiAcehTengah",
      "createdAt": "2026-09-22T18:45:45Z",
      "summary": "0 commit"
    },
    {
      "id": "21863725221",
      "type": "PushEvent",
      "repo": "Niumination/PemdiAcehTengah",
      "repoUrl": "https://api.github.com/repos/Niumination/PemdiAcehTengah",
      "createdAt": "2026-09-22T18:47:24Z",
      "summary": "0 commit"
    },
    {
      "id": "21860691207",
      "type": "PushEvent",
      "repo": "Niumination/Niu-OSS-Dashboard",
      "repoUrl": "https://api.github.com/repos/Niumination/Niu-OSS-Dashboard",
      "createdAt": "2026-09-22T16:25:18Z",
      "summary": "0 commit"
    },
    {
      "id": "21859212693",
      "type": "PushEvent",
      "repo": "Niumination/Niu-OSS-Dashboard",
      "repoUrl": "https://api.github.com/repos/Niumination/Niu-OSS-Dashboard",
      "createdAt": "2026-09-22T17:42:50Z",
      "summary": "0 commit"
    },
    {
      "id": "21856918441",
      "type": "PushEvent",
      "repo": "Niumination/Niu-OSS-Dashboard",
      "repoUrl": "https://api.github.com/repos/Niumination/Niu-OSS-Dashboard",
      "createdAt": "2026-09-22T17:10:29Z",
      "summary": "0 commit"
    },
    {
      "id": "21852792756",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-22T15:05:00Z",
      "summary": "0 commit"
    },
    {
      "id": "21852215468",
      "type": "PushEvent",
      "repo": "Niumination/Niu-OSS-Dashboard",
      "repoUrl": "https://api.github.com/repos/Niumination/Niu-OSS-Dashboard",
      "createdAt": "2026-09-22T16:04:45Z",
      "summary": "0 commit"
    },
    {
      "id": "21847763954",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-22T15:03:46Z",
      "summary": "0 commit"
    },
    {
      "id": "21847706145",
      "type": "PushEvent",
      "repo": "Niumination/Niu-OSS-Dashboard",
      "repoUrl": "https://api.github.com/repos/Niumination/Niu-OSS-Dashboard",
      "createdAt": "2026-09-22T15:02:59Z",
      "summary": "0 commit"
    },
    {
      "id": "21847230414",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-22T14:56:32Z",
      "summary": "0 commit"
    },
    {
      "id": "21834229992",
      "type": "PushEvent",
      "repo": "Niumination/PemdiAcehTengah",
      "repoUrl": "https://api.github.com/repos/Niumination/PemdiAcehTengah",
      "createdAt": "2026-09-22T10:30:34Z",
      "summary": "0 commit"
    },
    {
      "id": "15493655418",
      "type": "WatchEvent",
      "repo": "krillinai/OpenCreator",
      "repoUrl": "https://api.github.com/repos/krillinai/OpenCreator",
      "createdAt": "2026-09-22T09:47:46Z",
      "summary": "dipantau (watch)"
    },
    {
      "id": "21811864857",
      "type": "PushEvent",
      "repo": "Niumination/Niu-OSS-Dashboard",
      "repoUrl": "https://api.github.com/repos/Niumination/Niu-OSS-Dashboard",
      "createdAt": "2026-09-21T19:23:52Z",
      "summary": "0 commit"
    },
    {
      "id": "21810708298",
      "type": "PushEvent",
      "repo": "Niumination/Niu-OSS-Dashboard",
      "repoUrl": "https://api.github.com/repos/Niumination/Niu-OSS-Dashboard",
      "createdAt": "2026-09-21T19:08:19Z",
      "summary": "0 commit"
    },
    {
      "id": "21806371030",
      "type": "PushEvent",
      "repo": "Niumination/Niu-OSS-Dashboard",
      "repoUrl": "https://api.github.com/repos/Niumination/Niu-OSS-Dashboard",
      "createdAt": "2026-09-21T18:08:58Z",
      "summary": "0 commit"
    },
    {
      "id": "21805510023",
      "type": "PushEvent",
      "repo": "Niumination/Niu-OSS-Dashboard",
      "repoUrl": "https://api.github.com/repos/Niumination/Niu-OSS-Dashboard",
      "createdAt": "2026-09-21T17:58:10Z",
      "summary": "0 commit"
    },
    {
      "id": "21799191179",
      "type": "PushEvent",
      "repo": "Niumination/Niu-OSS-Dashboard",
      "repoUrl": "https://api.github.com/repos/Niumination/Niu-OSS-Dashboard",
      "createdAt": "2026-09-21T16:43:13Z",
      "summary": "0 commit"
    },
    {
      "id": "21784196819",
      "type": "PushEvent",
      "repo": "Niumination/Niu-OSS-Dashboard",
      "repoUrl": "https://api.github.com/repos/Niumination/Niu-OSS-Dashboard",
      "createdAt": "2026-09-21T20:08:59Z",
      "summary": "0 commit"
    },
    {
      "id": "21779774454",
      "type": "PushEvent",
      "repo": "Niumination/Niu-OSS-Dashboard",
      "repoUrl": "https://api.github.com/repos/Niumination/Niu-OSS-Dashboard",
      "createdAt": "2026-09-21T19:09:59Z",
      "summary": "0 commit"
    },
    {
      "id": "21779747216",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-21T19:23:50Z",
      "summary": "0 commit"
    },
    {
      "id": "21778789470",
      "type": "PushEvent",
      "repo": "Niumination/Niu-OSS-Dashboard",
      "repoUrl": "https://api.github.com/repos/Niumination/Niu-OSS-Dashboard",
      "createdAt": "2026-09-21T20:05:41Z",
      "summary": "0 commit"
    },
    {
      "id": "21778431226",
      "type": "PushEvent",
      "repo": "Niumination/Niu-OSS-Dashboard",
      "repoUrl": "https://api.github.com/repos/Niumination/Niu-OSS-Dashboard",
      "createdAt": "2026-09-21T18:58:54Z",
      "summary": "0 commit"
    },
    {
      "id": "21776958972",
      "type": "PushEvent",
      "repo": "Niumination/Niu-OSS-Dashboard",
      "repoUrl": "https://api.github.com/repos/Niumination/Niu-OSS-Dashboard",
      "createdAt": "2026-09-21T18:53:14Z",
      "summary": "0 commit"
    },
    {
      "id": "21776463145",
      "type": "PushEvent",
      "repo": "Niumination/Niu-OSS-Dashboard",
      "repoUrl": "https://api.github.com/repos/Niumination/Niu-OSS-Dashboard",
      "createdAt": "2026-09-21T19:47:14Z",
      "summary": "0 commit"
    },
    {
      "id": "21776076754",
      "type": "PushEvent",
      "repo": "Niumination/Niu-OSS-Dashboard",
      "repoUrl": "https://api.github.com/repos/Niumination/Niu-OSS-Dashboard",
      "createdAt": "2026-09-21T19:25:55Z",
      "summary": "0 commit"
    },
    {
      "id": "21775647032",
      "type": "PushEvent",
      "repo": "Niumination/Niu-OSS-Dashboard",
      "repoUrl": "https://api.github.com/repos/Niumination/Niu-OSS-Dashboard",
      "createdAt": "2026-09-21T19:11:17Z",
      "summary": "0 commit"
    },
    {
      "id": "21775452109",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-21T20:09:08Z",
      "summary": "0 commit"
    },
    {
      "id": "21775074403",
      "type": "PushEvent",
      "repo": "Niumination/Niu-OSS-Dashboard",
      "repoUrl": "https://api.github.com/repos/Niumination/Niu-OSS-Dashboard",
      "createdAt": "2026-09-21T19:21:52Z",
      "summary": "0 commit"
    },
    {
      "id": "21773922515",
      "type": "PushEvent",
      "repo": "Niumination/Niu-OSS-Dashboard",
      "repoUrl": "https://api.github.com/repos/Niumination/Niu-OSS-Dashboard",
      "createdAt": "2026-09-21T19:54:33Z",
      "summary": "0 commit"
    },
    {
      "id": "21772409778",
      "type": "PushEvent",
      "repo": "Niumination/Niu-OSS-Dashboard",
      "repoUrl": "https://api.github.com/repos/Niumination/Niu-OSS-Dashboard",
      "createdAt": "2026-09-21T19:00:26Z",
      "summary": "0 commit"
    },
    {
      "id": "21772107189",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-21T18:48:22Z",
      "summary": "0 commit"
    },
    {
      "id": "21771949395",
      "type": "PushEvent",
      "repo": "Niumination/Niu-OSS-Dashboard",
      "repoUrl": "https://api.github.com/repos/Niumination/Niu-OSS-Dashboard",
      "createdAt": "2026-09-21T18:39:12Z",
      "summary": "0 commit"
    },
    {
      "id": "21770955754",
      "type": "PushEvent",
      "repo": "Niumination/Niumination",
      "repoUrl": "https://api.github.com/repos/Niumination/Niumination",
      "createdAt": "2026-09-21T18:48:07Z",
      "summary": "0 commit"
    },
    {
      "id": "21769803231",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-21T18:22:16Z",
      "summary": "0 commit"
    },
    {
      "id": "15459150996",
      "type": "WatchEvent",
      "repo": "cactus-compute/needle",
      "repoUrl": "https://api.github.com/repos/cactus-compute/needle",
      "createdAt": "2026-09-21T20:20:21Z",
      "summary": "dipantau (watch)"
    },
    {
      "id": "21768621862",
      "type": "PushEvent",
      "repo": "Niumination/Niu-OSS-Dashboard",
      "repoUrl": "https://api.github.com/repos/Niumination/Niu-OSS-Dashboard",
      "createdAt": "2026-09-21T18:07:57Z",
      "summary": "0 commit"
    },
    {
      "id": "21767799663",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-21T18:00:59Z",
      "summary": "0 commit"
    },
    {
      "id": "21765554077",
      "type": "PushEvent",
      "repo": "Niumination/Niu-OSS-Dashboard",
      "repoUrl": "https://api.github.com/repos/Niumination/Niu-OSS-Dashboard",
      "createdAt": "2026-09-21T17:22:29Z",
      "summary": "0 commit"
    },
    {
      "id": "21764087209",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-21T17:25:28Z",
      "summary": "0 commit"
    },
    {
      "id": "21734157122",
      "type": "PushEvent",
      "repo": "Niumination/Niu-OSS-Dashboard",
      "repoUrl": "https://api.github.com/repos/Niumination/Niu-OSS-Dashboard",
      "createdAt": "2026-09-21T07:48:46Z",
      "summary": "0 commit"
    },
    {
      "id": "21733894126",
      "type": "CreateEvent",
      "repo": "Niumination/PemdiAcehTengah",
      "repoUrl": "https://api.github.com/repos/Niumination/PemdiAcehTengah",
      "createdAt": "2026-09-21T07:45:20Z",
      "summary": "membuat branch “backup/dual-persona-2026-09-21”"
    },
    {
      "id": "21733489110",
      "type": "PushEvent",
      "repo": "Niumination/Niu-OSS-Dashboard",
      "repoUrl": "https://api.github.com/repos/Niumination/Niu-OSS-Dashboard",
      "createdAt": "2026-09-21T07:39:55Z",
      "summary": "0 commit"
    },
    {
      "id": "21731003468",
      "type": "PushEvent",
      "repo": "Niumination/PemdiAcehTengah",
      "repoUrl": "https://api.github.com/repos/Niumination/PemdiAcehTengah",
      "createdAt": "2026-09-21T10:10:53Z",
      "summary": "0 commit"
    },
    {
      "id": "21719327232",
      "type": "PushEvent",
      "repo": "Niumination/PemdiAcehTengah",
      "repoUrl": "https://api.github.com/repos/Niumination/PemdiAcehTengah",
      "createdAt": "2026-09-21T07:50:09Z",
      "summary": "0 commit"
    },
    {
      "id": "21719202635",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-21T07:48:59Z",
      "summary": "0 commit"
    },
    {
      "id": "21700342903",
      "type": "PushEvent",
      "repo": "Niumination/PemdiAcehTengah",
      "repoUrl": "https://api.github.com/repos/Niumination/PemdiAcehTengah",
      "createdAt": "2026-09-21T02:26:23Z",
      "summary": "0 commit"
    },
    {
      "id": "21699775637",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-20T14:36:39Z",
      "summary": "0 commit"
    },
    {
      "id": "21686852432",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-20T14:48:26Z",
      "summary": "0 commit"
    },
    {
      "id": "21686824804",
      "type": "PushEvent",
      "repo": "Niumination/niu-dash",
      "repoUrl": "https://api.github.com/repos/Niumination/niu-dash",
      "createdAt": "2026-09-20T14:47:48Z",
      "summary": "0 commit"
    },
    {
      "id": "21677645391",
      "type": "PushEvent",
      "repo": "Niumination/PemdiAcehTengah",
      "repoUrl": "https://api.github.com/repos/Niumination/PemdiAcehTengah",
      "createdAt": "2026-09-20T19:12:47Z",
      "summary": "0 commit"
    },
    {
      "id": "21675022417",
      "type": "PushEvent",
      "repo": "Niumination/PemdiAcehTengah",
      "repoUrl": "https://api.github.com/repos/Niumination/PemdiAcehTengah",
      "createdAt": "2026-09-20T18:26:56Z",
      "summary": "0 commit"
    },
    {
      "id": "21674178253",
      "type": "PushEvent",
      "repo": "Niumination/Niu-OSS-Dashboard",
      "repoUrl": "https://api.github.com/repos/Niumination/Niu-OSS-Dashboard",
      "createdAt": "2026-09-20T18:11:45Z",
      "summary": "0 commit"
    },
    {
      "id": "21673671550",
      "type": "PushEvent",
      "repo": "Niumination/PemdiAcehTengah",
      "repoUrl": "https://api.github.com/repos/Niumination/PemdiAcehTengah",
      "createdAt": "2026-09-20T18:02:50Z",
      "summary": "0 commit"
    },
    {
      "id": "21671997526",
      "type": "PushEvent",
      "repo": "Niumination/PemdiAcehTengah",
      "repoUrl": "https://api.github.com/repos/Niumination/PemdiAcehTengah",
      "createdAt": "2026-09-20T17:33:15Z",
      "summary": "0 commit"
    },
    {
      "id": "21670311911",
      "type": "PushEvent",
      "repo": "Niumination/PemdiAcehTengah",
      "repoUrl": "https://api.github.com/repos/Niumination/PemdiAcehTengah",
      "createdAt": "2026-09-20T17:03:34Z",
      "summary": "0 commit"
    },
    {
      "id": "21663687638",
      "type": "PushEvent",
      "repo": "Niumination/Niumination",
      "repoUrl": "https://api.github.com/repos/Niumination/Niumination",
      "createdAt": "2026-09-20T15:09:06Z",
      "summary": "0 commit"
    },
    {
      "id": "21663281271",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-20T15:02:08Z",
      "summary": "0 commit"
    },
    {
      "id": "21662557147",
      "type": "PushEvent",
      "repo": "Niumination/sapa-ai",
      "repoUrl": "https://api.github.com/repos/Niumination/sapa-ai",
      "createdAt": "2026-09-20T14:49:32Z",
      "summary": "0 commit"
    },
    {
      "id": "21662485107",
      "type": "PushEvent",
      "repo": "Niumination/Niu-OSS-Dashboard",
      "repoUrl": "https://api.github.com/repos/Niumination/Niu-OSS-Dashboard",
      "createdAt": "2026-09-20T14:48:15Z",
      "summary": "0 commit"
    },
    {
      "id": "21662481609",
      "type": "PushEvent",
      "repo": "Niumination/PemdiAcehTengah",
      "repoUrl": "https://api.github.com/repos/Niumination/PemdiAcehTengah",
      "createdAt": "2026-09-20T14:48:11Z",
      "summary": "0 commit"
    },
    {
      "id": "21661062481",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-20T14:22:58Z",
      "summary": "0 commit"
    },
    {
      "id": "21660020770",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-20T14:04:10Z",
      "summary": "0 commit"
    },
    {
      "id": "21659588038",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-20T13:56:31Z",
      "summary": "0 commit"
    },
    {
      "id": "15377219539",
      "type": "WatchEvent",
      "repo": "atria-asi/Atria-Dawn-Preview",
      "repoUrl": "https://api.github.com/repos/atria-asi/Atria-Dawn-Preview",
      "createdAt": "2026-09-20T11:26:29Z",
      "summary": "dipantau (watch)"
    },
    {
      "id": "21644789733",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-19T10:43:40Z",
      "summary": "0 commit"
    },
    {
      "id": "21644588965",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-19T10:37:07Z",
      "summary": "0 commit"
    },
    {
      "id": "21642583124",
      "type": "PushEvent",
      "repo": "Niumination/niu-mission-control",
      "repoUrl": "https://api.github.com/repos/Niumination/niu-mission-control",
      "createdAt": "2026-09-19T17:07:22Z",
      "summary": "0 commit"
    },
    {
      "id": "21640355836",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-19T16:07:02Z",
      "summary": "0 commit"
    },
    {
      "id": "21633910541",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-19T12:58:46Z",
      "summary": "0 commit"
    },
    {
      "id": "21631580402",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-19T11:40:44Z",
      "summary": "0 commit"
    },
    {
      "id": "21628280835",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-19T09:49:25Z",
      "summary": "0 commit"
    }
  ],
  "live": false,
  "rateLimited": false,
  "updatedAt": "2026-09-24T13:31:07.502Z",
  "source": "fallback-cache"
};
