// AUTO-GENERATED oleh scripts/gen-mock.mjs pada 2026-09-19T13:47:15.145Z
// Sumber: data/*.json lokal
// Snapshot nyata akun GitHub — dipakai OTOMATIS saat GitHub API rate-limit
// atau saat build static export (GitHub Pages). Regenerasi: npm run gen:mock
import type { Snapshot } from './types';

export const MOCK_SNAPSHOT: Snapshot = {
  "user": {
    "login": "Niumination",
    "name": "Niumination",
    "avatar": "https://avatars.githubusercontent.com/u/123625275?v=4",
    "bio": null,
    "location": "Aceh Tengah",
    "company": null,
    "blog": "https://github.com/niumination",
    "twitter": null,
    "followers": 2,
    "following": 19,
    "publicRepos": 91,
    "joinedAt": "2023-01-26T08:06:49Z"
  },
  "repos": [
    {
      "name": "ecosystem-config",
      "fullName": "Niumination/ecosystem-config",
      "url": "https://github.com/Niumination/ecosystem-config",
      "description": "Niumination Ecosystem — orchestration/index repo: AGENTS.md, BACKLOG.md, scripts, docs. v4.0 maturity pipeline.",
      "language": "JavaScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 43997,
      "createdAt": "2026-07-16T17:39:24Z",
      "pushedAt": "2026-09-17T17:17:07Z"
    },
    {
      "name": "PemdiAcehTengah",
      "fullName": "Niumination/PemdiAcehTengah",
      "url": "https://github.com/Niumination/PemdiAcehTengah",
      "description": "Portal Pemerintah Digital Kabupaten Aceh Tengah - Bukan Portal Resmi",
      "language": "JavaScript",
      "stars": 1,
      "forks": 0,
      "watchers": 1,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://pemdi-aceh-tengah.vercel.app",
      "fork": false,
      "archived": false,
      "license": "MIT",
      "size": 898343,
      "createdAt": "2026-06-03T17:41:18Z",
      "pushedAt": "2026-09-17T17:03:28Z"
    },
    {
      "name": "Niumination",
      "fullName": "Niumination/Niumination",
      "url": "https://github.com/Niumination/Niumination",
      "description": "Niumination GitHub Profile README — animated terminal hero. Deployed from agents/profile/.",
      "language": "JavaScript",
      "stars": 1,
      "forks": 0,
      "watchers": 1,
      "openIssues": 0,
      "topics": [
        "aceh-tengah",
        "github-profile",
        "niumination",
        "readme",
        "spbe"
      ],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 81,
      "createdAt": "2026-07-15T10:38:11Z",
      "pushedAt": "2026-09-17T13:07:41Z"
    },
    {
      "name": "mata-watchdog-pi",
      "fullName": "Niumination/mata-watchdog-pi",
      "url": "https://github.com/Niumination/mata-watchdog-pi",
      "description": "MATA Watchdog — Pi App Studio dashboard for public procurement transparency in Central Aceh",
      "language": "JavaScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 28,
      "createdAt": "2026-09-16T11:44:01Z",
      "pushedAt": "2026-09-16T16:33:41Z"
    },
    {
      "name": "mata-aihackfest-2026",
      "fullName": "Niumination/mata-aihackfest-2026",
      "url": "https://github.com/Niumination/mata-aihackfest-2026",
      "description": "MATA — Watchdog Akuntabilitas Pengadaan. AI HackFest 2026 Batch 3 (Productivity & Personal AI).",
      "language": "HTML",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://watchdog-mata.niumination.web.id",
      "fork": false,
      "archived": false,
      "license": null,
      "size": 7672,
      "createdAt": "2026-09-11T08:10:53Z",
      "pushedAt": "2026-09-16T07:34:20Z"
    },
    {
      "name": "ai-file-organizer-android",
      "fullName": "Niumination/ai-file-organizer-android",
      "url": "https://github.com/Niumination/ai-file-organizer-android",
      "description": "AI File Organizer for Android — merapikan file SD Card / internal storage pakai Google Gemini AI. Kotlin, Jetpack Compose, SAF Scoped Storage.",
      "language": "Kotlin",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 2772,
      "createdAt": "2026-06-23T06:36:58Z",
      "pushedAt": "2026-09-13T15:20:10Z"
    },
    {
      "name": "Mobile-Harness",
      "fullName": "Niumination/Mobile-Harness",
      "url": "https://github.com/Niumination/Mobile-Harness",
      "description": "Claude Code on Android:  AI-powered mobile coding IDE for Android — chat with a coding agent, run Linux commands, edit files, review diffs, and preview web apps directly from your phone. No root required.",
      "language": "Kotlin",
      "stars": 2,
      "forks": 0,
      "watchers": 2,
      "openIssues": 0,
      "topics": [],
      "homepage": "",
      "fork": false,
      "archived": false,
      "license": "MIT",
      "size": 7773,
      "createdAt": "2026-09-08T08:46:15Z",
      "pushedAt": "2026-09-12T19:32:52Z"
    },
    {
      "name": "niu-cast",
      "fullName": "Niumination/niu-cast",
      "url": "https://github.com/Niumination/niu-cast",
      "description": null,
      "language": "Java",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 1,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 69895,
      "createdAt": "2026-06-12T17:13:07Z",
      "pushedAt": "2026-09-11T08:16:53Z"
    },
    {
      "name": "hermes-agent",
      "fullName": "Niumination/hermes-agent",
      "url": "https://github.com/Niumination/hermes-agent",
      "description": "The agent that grows with you",
      "language": "Python",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://hermes-agent.nousresearch.com",
      "fork": true,
      "archived": false,
      "license": "MIT",
      "size": 774843,
      "createdAt": "2026-08-24T17:55:30Z",
      "pushedAt": "2026-09-09T18:13:10Z"
    },
    {
      "name": "Smart-ASN-Gayo-Mengaji",
      "fullName": "Niumination/Smart-ASN-Gayo-Mengaji",
      "url": "https://github.com/Niumination/Smart-ASN-Gayo-Mengaji",
      "description": "Gayo-Mengaji",
      "language": "TypeScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 183,
      "createdAt": "2026-09-08T16:58:08Z",
      "pushedAt": "2026-09-09T06:20:54Z"
    },
    {
      "name": "niu-mission-control",
      "fullName": "Niumination/niu-mission-control",
      "url": "https://github.com/Niumination/niu-mission-control",
      "description": null,
      "language": "JavaScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 12133,
      "createdAt": "2026-07-16T18:33:36Z",
      "pushedAt": "2026-09-07T10:32:52Z"
    },
    {
      "name": "niu-gayo-agroclimate",
      "fullName": "Niumination/niu-gayo-agroclimate",
      "url": "https://github.com/Niumination/niu-gayo-agroclimate",
      "description": "Sistem Presisi Cuaca Pertanian Kopi Arabika Gayo & Mitigasi Bencana Aceh Tengah (WeatherNext Pipeline)",
      "language": "JavaScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 33,
      "createdAt": "2026-09-07T08:11:54Z",
      "pushedAt": "2026-09-07T08:12:21Z"
    },
    {
      "name": "Niu-LKH",
      "fullName": "Niumination/Niu-LKH",
      "url": "https://github.com/Niumination/Niu-LKH",
      "description": "Laporan Kegiatan Harian - Afrizal Munthe",
      "language": "JavaScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://niumination.github.io/Niu-LKH/",
      "fork": false,
      "archived": false,
      "license": null,
      "size": 4100,
      "createdAt": "2025-10-21T09:31:49Z",
      "pushedAt": "2026-09-07T07:17:30Z"
    },
    {
      "name": "sapa-ai",
      "fullName": "Niumination/sapa-ai",
      "url": "https://github.com/Niumination/sapa-ai",
      "description": null,
      "language": "TypeScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://sapa-ai-indol.vercel.app",
      "fork": false,
      "archived": false,
      "license": null,
      "size": 1235,
      "createdAt": "2026-09-01T17:26:26Z",
      "pushedAt": "2026-09-05T19:08:29Z"
    },
    {
      "name": "niu-journal",
      "fullName": "Niumination/niu-journal",
      "url": "https://github.com/Niumination/niu-journal",
      "description": "Aplikasi Tahap dua - Akademi Gen AI edisi APAC",
      "language": "TypeScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 183,
      "createdAt": "2026-09-05T10:08:31Z",
      "pushedAt": "2026-09-05T10:09:48Z"
    },
    {
      "name": "niu-journal-reflection-assistant",
      "fullName": "Niumination/niu-journal-reflection-assistant",
      "url": "https://github.com/Niumination/niu-journal-reflection-assistant",
      "description": "Aplikasi Prototipe tahap awal program Akademi Gen AI APAC Edition - Cohort 3",
      "language": "TypeScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 156,
      "createdAt": "2026-09-05T08:06:40Z",
      "pushedAt": "2026-09-05T08:07:31Z"
    },
    {
      "name": "cc-acehtengah",
      "fullName": "Niumination/cc-acehtengah",
      "url": "https://github.com/Niumination/cc-acehtengah",
      "description": null,
      "language": "TypeScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://cc-acehtengah.vercel.app",
      "fork": false,
      "archived": false,
      "license": null,
      "size": 1372,
      "createdAt": "2026-07-13T15:35:34Z",
      "pushedAt": "2026-09-01T16:50:27Z"
    },
    {
      "name": "jcode-eco",
      "fullName": "Niumination/jcode-eco",
      "url": "https://github.com/Niumination/jcode-eco",
      "description": "Jcode Ecosystem - AI Agent workspace",
      "language": "Python",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 312,
      "createdAt": "2026-08-30T08:38:08Z",
      "pushedAt": "2026-08-30T08:44:41Z"
    },
    {
      "name": "Flame-ADE",
      "fullName": "Niumination/Flame-ADE",
      "url": "https://github.com/Niumination/Flame-ADE",
      "description": "~7MB AI-native terminal emulator (ADE) — Tauri 2 + Rust + React 19. macOS Tahoe 26.5 primary target. BYOK AI, no telemetry, OS keychain.",
      "language": "TypeScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 1,
      "topics": [
        "ade",
        "ai",
        "ai-agent",
        "byok",
        "codemirror",
        "hackintosh",
        "macos",
        "opensource",
        "portable-pty",
        "react",
        "rust",
        "tailwindcss",
        "tauri",
        "tauri-app",
        "terminal",
        "terminal-emulator",
        "typescript",
        "vite",
        "xterm",
        "zustand"
      ],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": "Apache-2.0",
      "size": 703,
      "createdAt": "2026-05-23T00:11:54Z",
      "pushedAt": "2026-08-28T10:23:37Z"
    },
    {
      "name": "pabrik-aplikasi-gas",
      "fullName": "Niumination/pabrik-aplikasi-gas",
      "url": "https://github.com/Niumination/pabrik-aplikasi-gas",
      "description": "Pabrik Aplikasi - Inventaris Aset TI (GAS pilot project)",
      "language": "JavaScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 122,
      "createdAt": "2026-08-26T12:19:48Z",
      "pushedAt": "2026-08-26T18:44:19Z"
    },
    {
      "name": "niu-dash",
      "fullName": "Niumination/niu-dash",
      "url": "https://github.com/Niumination/niu-dash",
      "description": "Dark web glitch dashboard — 76 projects tracked. Niumination project inventory & DEV TRACKER.",
      "language": "HTML",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 1,
      "topics": [],
      "homepage": "https://niumination.github.io/niu-dash/",
      "fork": false,
      "archived": false,
      "license": "MIT",
      "size": 1733,
      "createdAt": "2026-06-03T09:03:02Z",
      "pushedAt": "2026-08-21T15:14:05Z"
    },
    {
      "name": "APEX-UI",
      "fullName": "Niumination/APEX-UI",
      "url": "https://github.com/Niumination/APEX-UI",
      "description": "The front interface of the AI assistant APEX by Reznikov Engineering ",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://apex-ui-xi.vercel.app",
      "fork": true,
      "archived": false,
      "license": "MIT",
      "size": 107,
      "createdAt": "2026-08-20T14:04:21Z",
      "pushedAt": "2026-08-20T10:22:24Z"
    },
    {
      "name": "pdf-inspector",
      "fullName": "Niumination/pdf-inspector",
      "url": "https://github.com/Niumination/pdf-inspector",
      "description": "Inspeksi PDF lokal tanpa LLM (no-agent) — pypdf. Baca isi PDF ke teks/ringkasan untuk agen.",
      "language": "Python",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 2,
      "createdAt": "2026-08-20T04:30:28Z",
      "pushedAt": "2026-08-20T04:30:40Z"
    },
    {
      "name": "spatial-vision",
      "fullName": "Niumination/spatial-vision",
      "url": "https://github.com/Niumination/spatial-vision",
      "description": "Full-stack Rust/WASM spatial UI — Axum backend + wasm-bindgen frontend, gesture/pinch detection, WebSocket broadcast",
      "language": "HTML",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 19789,
      "createdAt": "2026-07-22T06:25:04Z",
      "pushedAt": "2026-08-18T12:26:03Z"
    },
    {
      "name": "UACC",
      "fullName": "Niumination/UACC",
      "url": "https://github.com/Niumination/UACC",
      "description": null,
      "language": "Python",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": true,
      "archived": false,
      "license": "MIT",
      "size": 3319,
      "createdAt": "2026-07-27T09:47:22Z",
      "pushedAt": "2026-08-18T12:25:35Z"
    },
    {
      "name": "mac-web-dashboard",
      "fullName": "Niumination/mac-web-dashboard",
      "url": "https://github.com/Niumination/mac-web-dashboard",
      "description": null,
      "language": "TypeScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 117,
      "createdAt": "2026-06-21T16:01:17Z",
      "pushedAt": "2026-08-18T12:25:18Z"
    },
    {
      "name": "arch-web-dashboard",
      "fullName": "Niumination/arch-web-dashboard",
      "url": "https://github.com/Niumination/arch-web-dashboard",
      "description": null,
      "language": "TypeScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 34,
      "createdAt": "2026-06-21T15:44:00Z",
      "pushedAt": "2026-08-18T12:25:15Z"
    },
    {
      "name": "latticesend",
      "fullName": "Niumination/latticesend",
      "url": "https://github.com/Niumination/latticesend",
      "description": "P2P file transfer tool — built with Rust/Flutter. Part of Niumination Ecosystem services.",
      "language": "HTML",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": "MIT",
      "size": 214,
      "createdAt": "2026-07-28T17:08:23Z",
      "pushedAt": "2026-08-10T09:11:59Z"
    },
    {
      "name": "cc-switch",
      "fullName": "Niumination/cc-switch",
      "url": "https://github.com/Niumination/cc-switch",
      "description": "A cross-platform desktop All-in-One assistant for Claude Code, Codex, OpenCode, OpenClaw, Gemini CLI & Hermes Agent. Only official website: ccswitch.io",
      "language": "Rust",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://ccswitch.io",
      "fork": true,
      "archived": false,
      "license": "MIT",
      "size": 66120,
      "createdAt": "2026-07-19T17:46:39Z",
      "pushedAt": "2026-08-07T20:36:46Z"
    },
    {
      "name": "Android-Dex",
      "fullName": "Niumination/Android-Dex",
      "url": "https://github.com/Niumination/Android-Dex",
      "description": "Enable a full desktop experience from any Android device over Wi‑Fi. No root, scrcpy-powered, Flutter desktop app with wireless ADB, per‑app audio, and quick controls.",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://shrey113.github.io/Android-Dex/",
      "fork": true,
      "archived": false,
      "license": null,
      "size": 141776,
      "createdAt": "2026-08-05T08:41:42Z",
      "pushedAt": "2026-08-04T19:21:44Z"
    },
    {
      "name": "niu-dash-fullstack",
      "fullName": "Niumination/niu-dash-fullstack",
      "url": "https://github.com/Niumination/niu-dash-fullstack",
      "description": "Next.js 16 Fullstack Dashboard — Prisma, Three.js, TanStack Query, next-auth",
      "language": "TypeScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 317,
      "createdAt": "2026-07-06T03:03:22Z",
      "pushedAt": "2026-07-30T09:05:41Z"
    },
    {
      "name": "airi",
      "fullName": "Niumination/airi",
      "url": "https://github.com/Niumination/airi",
      "description": "💖🧸 Self hosted, you-owned Grok Companion, a container of souls of waifu, cyber livings to bring them into our worlds, wishing to achieve Neuro-sama's altitude. Capable of realtime voice chat, Minecraft, Factorio playing. Web / macOS / Windows supported.",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://airi.moeru.ai/docs/",
      "fork": true,
      "archived": false,
      "license": "MIT",
      "size": 519728,
      "createdAt": "2026-07-27T12:22:30Z",
      "pushedAt": "2026-07-27T11:50:02Z"
    },
    {
      "name": "agentic-awesome-skills",
      "fullName": "Niumination/agentic-awesome-skills",
      "url": "https://github.com/Niumination/agentic-awesome-skills",
      "description": "AAS Core is the local, agent-first control plane for complete catalog discovery, agent-owned selection, stack validation, and planning, backed by 1,987+ agentic skills. Includes CLI, local MCP, catalog, plugins, and Workbench.",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://sickn33.github.io/agentic-awesome-skills/",
      "fork": true,
      "archived": false,
      "license": "MIT",
      "size": 111656,
      "createdAt": "2026-07-27T10:02:51Z",
      "pushedAt": "2026-07-27T05:13:52Z"
    },
    {
      "name": "opendataloader-pdf",
      "fullName": "Niumination/opendataloader-pdf",
      "url": "https://github.com/Niumination/opendataloader-pdf",
      "description": "PDF Parser for AI-ready data. Automate PDF accessibility. Open-source.",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://opendataloader.org",
      "fork": true,
      "archived": false,
      "license": "Apache-2.0",
      "size": 87651,
      "createdAt": "2026-07-27T09:55:52Z",
      "pushedAt": "2026-07-27T00:17:13Z"
    },
    {
      "name": "opencode",
      "fullName": "Niumination/opencode",
      "url": "https://github.com/Niumination/opencode",
      "description": "The open source coding agent.",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://opencode.ai",
      "fork": true,
      "archived": false,
      "license": "MIT",
      "size": 414981,
      "createdAt": "2026-07-18T11:02:44Z",
      "pushedAt": "2026-07-18T07:38:02Z"
    },
    {
      "name": "kune-ya.com",
      "fullName": "Niumination/kune-ya.com",
      "url": "https://github.com/Niumination/kune-ya.com",
      "description": null,
      "language": "TypeScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://kune-ya-com.vercel.app",
      "fork": false,
      "archived": false,
      "license": null,
      "size": 192,
      "createdAt": "2026-06-06T18:45:21Z",
      "pushedAt": "2026-07-13T17:08:24Z"
    },
    {
      "name": "didong-code",
      "fullName": "Niumination/didong-code",
      "url": "https://github.com/Niumination/didong-code",
      "description": "Didong-Code — Agentic Development Environment dengan jiwa tradisi Gayo Aceh. Electron + React + TypeScript AI coding agent desktop.",
      "language": "TypeScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://github.com/Niumination/didong-code",
      "fork": false,
      "archived": false,
      "license": "MIT",
      "size": 130,
      "createdAt": "2026-07-07T17:02:32Z",
      "pushedAt": "2026-07-07T17:58:50Z"
    },
    {
      "name": "AI-First-OS",
      "fullName": "Niumination/AI-First-OS",
      "url": "https://github.com/Niumination/AI-First-OS",
      "description": "Arch Linux ISO builder — AI First OS. Sistem operasi dengan Hermes Agent sebagai warga negara kelas satu.",
      "language": "Shell",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 5,
      "createdAt": "2026-06-21T17:44:50Z",
      "pushedAt": "2026-06-27T07:39:47Z"
    },
    {
      "name": "Maze-3D-Game---Web-Based",
      "fullName": "Niumination/Maze-3D-Game---Web-Based",
      "url": "https://github.com/Niumination/Maze-3D-Game---Web-Based",
      "description": null,
      "language": "HTML",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 27,
      "createdAt": "2026-05-20T08:50:45Z",
      "pushedAt": "2026-06-27T07:38:33Z"
    },
    {
      "name": "HermesV-Github",
      "fullName": "Niumination/HermesV-Github",
      "url": "https://github.com/Niumination/HermesV-Github",
      "description": "Hermes Agent Portable on Github Codespace",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 8,
      "createdAt": "2026-06-06T04:09:05Z",
      "pushedAt": "2026-06-11T10:53:20Z"
    },
    {
      "name": "niu-private",
      "fullName": "Niumination/niu-private",
      "url": "https://github.com/Niumination/niu-private",
      "description": "Niu Private — Document Vault & Kanban Project Board",
      "language": "TypeScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://niumination.github.io/niu-private/",
      "fork": false,
      "archived": false,
      "license": null,
      "size": 130,
      "createdAt": "2026-06-06T06:52:57Z",
      "pushedAt": "2026-06-08T05:25:27Z"
    },
    {
      "name": "VirtualAssistance",
      "fullName": "Niumination/VirtualAssistance",
      "url": "https://github.com/Niumination/VirtualAssistance",
      "description": null,
      "language": "TypeScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://virtual-assistance-pi.vercel.app",
      "fork": false,
      "archived": false,
      "license": null,
      "size": 113,
      "createdAt": "2026-06-03T15:44:28Z",
      "pushedAt": "2026-06-03T16:51:00Z"
    },
    {
      "name": "flame-code",
      "fullName": "Niumination/flame-code",
      "url": "https://github.com/Niumination/flame-code",
      "description": "My First Build, Using AI",
      "language": "TypeScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 1541,
      "createdAt": "2026-05-31T17:17:37Z",
      "pushedAt": "2026-05-31T17:22:02Z"
    },
    {
      "name": "terax-ai",
      "fullName": "Niumination/terax-ai",
      "url": "https://github.com/Niumination/terax-ai",
      "description": "Lightweight (7MB) AI terminal emulator (ADE) built in Rust & Tauri & React",
      "language": "TypeScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://terax.app",
      "fork": true,
      "archived": false,
      "license": "Apache-2.0",
      "size": 12345,
      "createdAt": "2026-05-20T07:36:30Z",
      "pushedAt": "2026-05-31T07:20:40Z"
    },
    {
      "name": "free-vps",
      "fullName": "Niumination/free-vps",
      "url": "https://github.com/Niumination/free-vps",
      "description": null,
      "language": "TypeScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 278,
      "createdAt": "2026-05-29T07:45:29Z",
      "pushedAt": "2026-05-29T09:47:11Z"
    },
    {
      "name": "jcode",
      "fullName": "Niumination/jcode",
      "url": "https://github.com/Niumination/jcode",
      "description": "Coding Agent Harness",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "",
      "fork": true,
      "archived": false,
      "license": "MIT",
      "size": 381348,
      "createdAt": "2026-05-17T14:19:36Z",
      "pushedAt": "2026-05-17T03:36:04Z"
    },
    {
      "name": "skills",
      "fullName": "Niumination/skills",
      "url": "https://github.com/Niumination/skills",
      "description": "Skills for Real Engineers. Straight from my .claude directory.",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "",
      "fork": true,
      "archived": false,
      "license": "MIT",
      "size": 200,
      "createdAt": "2026-05-18T11:53:28Z",
      "pushedAt": "2026-05-13T13:05:22Z"
    },
    {
      "name": "Free-Claude-Opus",
      "fullName": "Niumination/Free-Claude-Opus",
      "url": "https://github.com/Niumination/Free-Claude-Opus",
      "description": null,
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": true,
      "archived": false,
      "license": null,
      "size": 9,
      "createdAt": "2026-04-26T12:09:09Z",
      "pushedAt": "2026-04-23T06:55:10Z"
    },
    {
      "name": "G0DM0D3",
      "fullName": "Niumination/G0DM0D3",
      "url": "https://github.com/Niumination/G0DM0D3",
      "description": "LIBERATED AI CHAT",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": true,
      "archived": false,
      "license": "AGPL-3.0",
      "size": 1078,
      "createdAt": "2026-05-25T04:16:03Z",
      "pushedAt": "2026-03-26T02:55:07Z"
    },
    {
      "name": "disunday",
      "fullName": "Niumination/disunday",
      "url": "https://github.com/Niumination/disunday",
      "description": "Control opencode from Discord. Say goodbye to Sundays—manage your AI coding projects 24/7 through Discord channels.",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "",
      "fork": true,
      "archived": false,
      "license": "MIT",
      "size": 1978,
      "createdAt": "2026-05-29T01:44:06Z",
      "pushedAt": "2026-02-23T09:31:42Z"
    },
    {
      "name": "Bella",
      "fullName": "Niumination/Bella",
      "url": "https://github.com/Niumination/Bella",
      "description": "Bella is best",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "",
      "fork": true,
      "archived": false,
      "license": null,
      "size": 107636,
      "createdAt": "2026-05-24T18:11:08Z",
      "pushedAt": "2026-02-05T02:58:42Z"
    },
    {
      "name": "roboto_origin",
      "fullName": "Niumination/roboto_origin",
      "url": "https://github.com/Niumination/roboto_origin",
      "description": "Roboto_origin Fully Open-Source DIY Humanoid Robot/萝博头原型机全开源手搓级人形机器人",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "",
      "fork": true,
      "archived": false,
      "license": null,
      "size": 754527,
      "createdAt": "2026-02-11T02:34:23Z",
      "pushedAt": "2026-02-04T10:55:40Z"
    },
    {
      "name": "lmarena.github.io",
      "fullName": "Niumination/lmarena.github.io",
      "url": "https://github.com/Niumination/lmarena.github.io",
      "description": null,
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": true,
      "archived": false,
      "license": "MIT",
      "size": 320259,
      "createdAt": "2026-05-25T17:22:05Z",
      "pushedAt": "2026-01-04T04:50:19Z"
    },
    {
      "name": "ryu-dots",
      "fullName": "Niumination/ryu-dots",
      "url": "https://github.com/Niumination/ryu-dots",
      "description": "Complete Arch Linux system configuration with Hyprland + Illogical Impulse",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 0,
      "createdAt": "2025-11-17T04:34:00Z",
      "pushedAt": "2025-11-17T04:34:00Z"
    },
    {
      "name": "niu-speedtest",
      "fullName": "Niumination/niu-speedtest",
      "url": "https://github.com/Niumination/niu-speedtest",
      "description": null,
      "language": "Python",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": "MIT",
      "size": 13,
      "createdAt": "2025-11-15T02:27:59Z",
      "pushedAt": "2025-11-16T02:21:00Z"
    },
    {
      "name": "Devs-Niu",
      "fullName": "Niumination/Devs-Niu",
      "url": "https://github.com/Niumination/Devs-Niu",
      "description": null,
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 0,
      "createdAt": "2025-11-08T06:58:00Z",
      "pushedAt": "2025-11-08T06:58:00Z"
    },
    {
      "name": "SPBE-DevOps-Academy",
      "fullName": "Niumination/SPBE-DevOps-Academy",
      "url": "https://github.com/Niumination/SPBE-DevOps-Academy",
      "description": null,
      "language": "JavaScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 105,
      "createdAt": "2025-11-04T18:11:42Z",
      "pushedAt": "2025-11-05T13:59:55Z"
    },
    {
      "name": "Continue-Agent",
      "fullName": "Niumination/Continue-Agent",
      "url": "https://github.com/Niumination/Continue-Agent",
      "description": null,
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 0,
      "createdAt": "2025-10-26T17:07:37Z",
      "pushedAt": "2025-10-26T17:10:25Z"
    },
    {
      "name": "kms-spbe",
      "fullName": "Niumination/kms-spbe",
      "url": "https://github.com/Niumination/kms-spbe",
      "description": null,
      "language": "TypeScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://kms-spbe.vercel.app",
      "fork": false,
      "archived": false,
      "license": null,
      "size": 469,
      "createdAt": "2025-10-24T19:45:35Z",
      "pushedAt": "2025-10-26T16:41:02Z"
    },
    {
      "name": "SilentSDDM",
      "fullName": "Niumination/SilentSDDM",
      "url": "https://github.com/Niumination/SilentSDDM",
      "description": "A very customizable SDDM theme that actually looks good.",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "",
      "fork": true,
      "archived": false,
      "license": "GPL-3.0",
      "size": 230669,
      "createdAt": "2025-10-26T07:49:14Z",
      "pushedAt": "2025-10-23T14:13:52Z"
    },
    {
      "name": "Niu-Startpage",
      "fullName": "Niumination/Niu-Startpage",
      "url": "https://github.com/Niumination/Niu-Startpage",
      "description": "My Gateway to the internet",
      "language": "HTML",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://niumination.github.io/Niu-Startpage/",
      "fork": false,
      "archived": false,
      "license": null,
      "size": 156,
      "createdAt": "2025-10-20T06:59:34Z",
      "pushedAt": "2025-10-22T09:27:33Z"
    },
    {
      "name": "Niu-Cyber-Search-Engine",
      "fullName": "Niumination/Niu-Cyber-Search-Engine",
      "url": "https://github.com/Niumination/Niu-Cyber-Search-Engine",
      "description": "My First Cyber Search Engine App",
      "language": "TypeScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://niu-cyber.vercel.app",
      "fork": false,
      "archived": false,
      "license": null,
      "size": 236,
      "createdAt": "2025-10-22T03:04:33Z",
      "pushedAt": "2025-10-22T04:03:39Z"
    },
    {
      "name": "zaryu.startpage",
      "fullName": "Niumination/zaryu.startpage",
      "url": "https://github.com/Niumination/zaryu.startpage",
      "description": "🐱✨ Aesthetic and clean startpage in Catppuccin style, hosted on GitHub Pages",
      "language": "JavaScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://niumination.github.io/zaryu.startpage/",
      "fork": true,
      "archived": false,
      "license": "MIT",
      "size": 65907,
      "createdAt": "2024-12-07T05:01:56Z",
      "pushedAt": "2025-10-13T14:47:27Z"
    },
    {
      "name": "NiuHomePage",
      "fullName": "Niumination/NiuHomePage",
      "url": "https://github.com/Niumination/NiuHomePage",
      "description": "I wanted a home page, so I made one.",
      "language": "CSS",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://niumination.github.io/NiuHomePage/",
      "fork": true,
      "archived": false,
      "license": "MIT",
      "size": 16593,
      "createdAt": "2025-09-18T15:05:52Z",
      "pushedAt": "2025-10-13T13:00:51Z"
    },
    {
      "name": "PAGASUS-PRO",
      "fullName": "Niumination/PAGASUS-PRO",
      "url": "https://github.com/Niumination/PAGASUS-PRO",
      "description": null,
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": true,
      "archived": false,
      "license": "NOASSERTION",
      "size": 220,
      "createdAt": "2025-10-07T14:06:51Z",
      "pushedAt": "2025-10-03T13:50:38Z"
    },
    {
      "name": "mcp-for-beginners-Microsoft",
      "fullName": "Niumination/mcp-for-beginners-Microsoft",
      "url": "https://github.com/Niumination/mcp-for-beginners-Microsoft",
      "description": "This open-source curriculum introduces the fundamentals of Model Context Protocol (MCP) through real-world, cross-language examples in .NET, Java, TypeScript, JavaScript, Rust and Python. Designed for developers, it focuses on practical techniques for building modular, scalable, and secure AI workflows from session setup to service orchestration.",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "",
      "fork": true,
      "archived": false,
      "license": "MIT",
      "size": 2168552,
      "createdAt": "2025-10-04T16:07:00Z",
      "pushedAt": "2025-10-03T08:42:01Z"
    },
    {
      "name": "ryuland-dotfiles",
      "fullName": "Niumination/ryuland-dotfiles",
      "url": "https://github.com/Niumination/ryuland-dotfiles",
      "description": "Rice built for usability",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://end-4.github.io/dots-hyprland-wiki/en/",
      "fork": true,
      "archived": false,
      "license": "GPL-3.0",
      "size": 19628,
      "createdAt": "2025-09-29T11:02:27Z",
      "pushedAt": "2025-09-29T08:28:56Z"
    },
    {
      "name": "Prakom-Surgawi",
      "fullName": "Niumination/Prakom-Surgawi",
      "url": "https://github.com/Niumination/Prakom-Surgawi",
      "description": "Anything you want",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 0,
      "createdAt": "2025-09-26T12:23:33Z",
      "pushedAt": "2025-09-26T12:23:34Z"
    },
    {
      "name": "cursor-free-vip",
      "fullName": "Niumination/cursor-free-vip",
      "url": "https://github.com/Niumination/cursor-free-vip",
      "description": "[Support 0.49.x]（Reset Cursor AI MachineID & Bypass Higher Token Limit） Cursor Ai ，自动重置机器ID ， 免费升级使用Pro功能: You've reached your trial request limit. / Too many free trial accounts used on this machine. Please upgrade to pro. We have this limit in place to prevent abuse. Please let us know if you believe this is a mistake.",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://www.cursor.com/",
      "fork": true,
      "archived": false,
      "license": "NOASSERTION",
      "size": 12241,
      "createdAt": "2025-10-27T01:54:22Z",
      "pushedAt": "2025-09-16T03:47:39Z"
    },
    {
      "name": "docker-mcp-tutorial",
      "fullName": "Niumination/docker-mcp-tutorial",
      "url": "https://github.com/Niumination/docker-mcp-tutorial",
      "description": "Complete tutorial materials for building MCP servers with Docker - from NetworkChuck's video",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": true,
      "archived": false,
      "license": "MIT",
      "size": 35,
      "createdAt": "2025-10-07T10:15:42Z",
      "pushedAt": "2025-09-12T15:21:49Z"
    },
    {
      "name": "hyprfloat",
      "fullName": "Niumination/hyprfloat",
      "url": "https://github.com/Niumination/hyprfloat",
      "description": "Hyprland floating window manager and workspace overview utility.",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": true,
      "archived": false,
      "license": "MIT",
      "size": 15165,
      "createdAt": "2025-09-11T08:18:35Z",
      "pushedAt": "2025-09-11T07:10:07Z"
    },
    {
      "name": "ryushell",
      "fullName": "Niumination/ryushell",
      "url": "https://github.com/Niumination/ryushell",
      "description": "‼️ No waybar here ‼️",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "",
      "fork": true,
      "archived": false,
      "license": "GPL-3.0",
      "size": 1869,
      "createdAt": "2025-09-10T15:13:58Z",
      "pushedAt": "2025-09-10T12:57:16Z"
    },
    {
      "name": "Windots",
      "fullName": "Niumination/Windots",
      "url": "https://github.com/Niumination/Windots",
      "description": "A collection of my personal Windows dotfiles and configs.",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "",
      "fork": true,
      "archived": false,
      "license": "MIT",
      "size": 73283,
      "createdAt": "2025-07-02T09:02:09Z",
      "pushedAt": "2025-08-04T05:04:36Z"
    },
    {
      "name": "unlimited-claude-AI",
      "fullName": "Niumination/unlimited-claude-AI",
      "url": "https://github.com/Niumination/unlimited-claude-AI",
      "description": "Claude AI. No backend, no server costs, 100% free.",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "",
      "fork": true,
      "archived": false,
      "license": "MIT",
      "size": 669,
      "createdAt": "2026-04-20T17:21:04Z",
      "pushedAt": "2025-07-22T06:01:32Z"
    },
    {
      "name": "ryuland",
      "fullName": "Niumination/ryuland",
      "url": "https://github.com/Niumination/ryuland",
      "description": "Unleash the power of Hyprland with our modern, useful, user friendly, islamic halal Hyprland ecosystem dots",
      "language": "JavaScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://hyprluna.org",
      "fork": true,
      "archived": false,
      "license": "MIT",
      "size": 203755,
      "createdAt": "2025-06-12T04:13:23Z",
      "pushedAt": "2025-07-22T05:11:03Z"
    },
    {
      "name": "cyb3rgh0u1.github.io",
      "fullName": "Niumination/cyb3rgh0u1.github.io",
      "url": "https://github.com/Niumination/cyb3rgh0u1.github.io",
      "description": null,
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://cyb3rgh0u1.github.io/",
      "fork": true,
      "archived": false,
      "license": "MIT",
      "size": 975,
      "createdAt": "2025-07-04T10:40:26Z",
      "pushedAt": "2025-07-01T22:30:24Z"
    },
    {
      "name": "Zaryu-HyDE",
      "fullName": "Niumination/Zaryu-HyDE",
      "url": "https://github.com/Niumination/Zaryu-HyDE",
      "description": "Portable and extensible  re-work  of prasanthrangan/hyprdots // Aesthetic, dynamic and minimal dots for Arch  Hyprland // Going beyond ",
      "language": "Shell",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "",
      "fork": true,
      "archived": false,
      "license": "GPL-3.0",
      "size": 1302316,
      "createdAt": "2024-12-02T09:14:56Z",
      "pushedAt": "2025-06-17T02:56:55Z"
    },
    {
      "name": "RyuDE",
      "fullName": "Niumination/RyuDE",
      "url": "https://github.com/Niumination/RyuDE",
      "description": "My Personal Desktop Environtment Based On HyDE-Project",
      "language": "C++",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 151241,
      "createdAt": "2025-05-26T14:36:55Z",
      "pushedAt": "2025-05-28T11:00:08Z"
    },
    {
      "name": "ZaryuHive",
      "fullName": "Niumination/ZaryuHive",
      "url": "https://github.com/Niumination/ZaryuHive",
      "description": null,
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 79847,
      "createdAt": "2024-12-05T05:00:59Z",
      "pushedAt": "2025-05-27T02:58:20Z"
    },
    {
      "name": "win11-dotfiles",
      "fullName": "Niumination/win11-dotfiles",
      "url": "https://github.com/Niumination/win11-dotfiles",
      "description": "my current desktop dotfiles",
      "language": "CSS",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": true,
      "archived": false,
      "license": null,
      "size": 88289,
      "createdAt": "2025-02-20T08:25:29Z",
      "pushedAt": "2025-05-06T04:11:02Z"
    },
    {
      "name": "hyprnix",
      "fullName": "Niumination/hyprnix",
      "url": "https://github.com/Niumination/hyprnix",
      "description": null,
      "language": "Nix",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 784,
      "createdAt": "2024-11-13T11:11:11Z",
      "pushedAt": "2025-02-24T06:30:53Z"
    },
    {
      "name": "hyprdots",
      "fullName": "Niumination/hyprdots",
      "url": "https://github.com/Niumination/hyprdots",
      "description": "// Aesthetic, dynamic and minimal dots for Arch hyprland",
      "language": "Shell",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "",
      "fork": true,
      "archived": false,
      "license": "GPL-3.0",
      "size": 973984,
      "createdAt": "2024-12-04T03:49:52Z",
      "pushedAt": "2025-02-13T07:15:15Z"
    },
    {
      "name": "Axenide-Dotfiles",
      "fullName": "Niumination/Axenide-Dotfiles",
      "url": "https://github.com/Niumination/Axenide-Dotfiles",
      "description": ".'s",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "",
      "fork": true,
      "archived": false,
      "license": null,
      "size": 451494,
      "createdAt": "2025-01-18T15:32:02Z",
      "pushedAt": "2025-01-17T00:31:13Z"
    },
    {
      "name": "agsv1-hyprpanel",
      "fullName": "Niumination/agsv1-hyprpanel",
      "url": "https://github.com/Niumination/agsv1-hyprpanel",
      "description": "for use agsv1",
      "language": "TypeScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": "MIT",
      "size": 10122,
      "createdAt": "2025-01-09T11:35:51Z",
      "pushedAt": "2025-01-09T11:36:03Z"
    },
    {
      "name": "hive-dotfiles",
      "fullName": "Niumination/hive-dotfiles",
      "url": "https://github.com/Niumination/hive-dotfiles",
      "description": null,
      "language": "CSS",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 136843,
      "createdAt": "2024-12-03T03:36:08Z",
      "pushedAt": "2025-01-08T08:00:56Z"
    },
    {
      "name": "dotfiles",
      "fullName": "Niumination/dotfiles",
      "url": "https://github.com/Niumination/dotfiles",
      "description": "My Arch Dotfiles",
      "language": "JavaScript",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 1641316,
      "createdAt": "2024-10-19T15:23:06Z",
      "pushedAt": "2024-12-17T09:08:22Z"
    },
    {
      "name": "kaizen",
      "fullName": "Niumination/kaizen",
      "url": "https://github.com/Niumination/kaizen",
      "description": "productive desktop environment setup.",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "",
      "fork": true,
      "archived": false,
      "license": "MIT",
      "size": 114614,
      "createdAt": "2024-12-07T15:15:21Z",
      "pushedAt": "2024-12-07T10:13:17Z"
    },
    {
      "name": "AnachonisticHypr",
      "fullName": "Niumination/AnachonisticHypr",
      "url": "https://github.com/Niumination/AnachonisticHypr",
      "description": null,
      "language": "Shell",
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": null,
      "fork": false,
      "archived": false,
      "license": null,
      "size": 137556,
      "createdAt": "2024-11-26T15:15:39Z",
      "pushedAt": "2024-11-29T12:28:44Z"
    },
    {
      "name": "matt-dotfiles",
      "fullName": "Niumination/matt-dotfiles",
      "url": "https://github.com/Niumination/matt-dotfiles",
      "description": "💄 Yet another Aesthetic Hyprland Config",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://dotfiles-docs.vercel.app/",
      "fork": true,
      "archived": false,
      "license": "GPL-3.0",
      "size": 322770,
      "createdAt": "2024-12-03T06:51:25Z",
      "pushedAt": "2024-11-28T10:25:41Z"
    },
    {
      "name": "Hyde-cli",
      "fullName": "Niumination/Hyde-cli",
      "url": "https://github.com/Niumination/Hyde-cli",
      "description": "A HyDE CLI, wrapper, tweaks , workarounds, and more!",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://github.com/prasanthrangan/hyprdots",
      "fork": true,
      "archived": false,
      "license": "GPL-3.0",
      "size": 15268,
      "createdAt": "2024-11-05T03:44:51Z",
      "pushedAt": "2024-10-31T15:20:19Z"
    },
    {
      "name": "Activate-Office-365-on-Windows-10-11",
      "fullName": "Niumination/Activate-Office-365-on-Windows-10-11",
      "url": "https://github.com/Niumination/Activate-Office-365-on-Windows-10-11",
      "description": "Leverage the cloud when you Download Microsoft 365 (Office 365). Microsoft 365 has the tools you need to seamlessly create, collaborate, and share from all your devices. And with security features such as encrypted email and data loss prevention, you and your team can work safely from anywhere.",
      "language": null,
      "stars": 0,
      "forks": 0,
      "watchers": 0,
      "openIssues": 0,
      "topics": [],
      "homepage": "https://www.microsoft.com/en-us/microsoft-365/download-office",
      "fork": true,
      "archived": false,
      "license": null,
      "size": 3538,
      "createdAt": "2026-04-24T08:01:54Z",
      "pushedAt": "2024-08-27T07:55:22Z"
    }
  ],
  "events": [
    {
      "id": "21411764900",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-17T17:02:46Z",
      "summary": "0 commit"
    },
    {
      "id": "21409163851",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-17T16:31:47Z",
      "summary": "0 commit"
    },
    {
      "id": "21406552453",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-17T15:53:44Z",
      "summary": "0 commit"
    },
    {
      "id": "15226169156",
      "type": "WatchEvent",
      "repo": "Homebrew/brew",
      "repoUrl": "https://api.github.com/repos/Homebrew/brew",
      "createdAt": "2026-09-17T14:15:54Z",
      "summary": "dipantau (watch)"
    },
    {
      "id": "21394539285",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-16T07:55:58Z",
      "summary": "0 commit"
    },
    {
      "id": "21381967072",
      "type": "PushEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-16T04:30:49Z",
      "summary": "0 commit"
    },
    {
      "id": "21381856723",
      "type": "PushEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-16T04:28:43Z",
      "summary": "0 commit"
    },
    {
      "id": "21379710257",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-17T08:59:52Z",
      "summary": "0 commit"
    },
    {
      "id": "21379064387",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-17T05:44:59Z",
      "summary": "0 commit"
    },
    {
      "id": "21377783995",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-17T05:20:33Z",
      "summary": "0 commit"
    },
    {
      "id": "21377236649",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-17T05:10:02Z",
      "summary": "0 commit"
    },
    {
      "id": "15201149800",
      "type": "WatchEvent",
      "repo": "Lakr233/vphone-cli",
      "repoUrl": "https://api.github.com/repos/Lakr233/vphone-cli",
      "createdAt": "2026-09-17T07:26:57Z",
      "summary": "dipantau (watch)"
    },
    {
      "id": "21372327937",
      "type": "PushEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-15T18:41:03Z",
      "summary": "0 commit"
    },
    {
      "id": "21365553454",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-17T05:32:39Z",
      "summary": "0 commit"
    },
    {
      "id": "21365496743",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-17T05:31:42Z",
      "summary": "0 commit"
    },
    {
      "id": "21364417648",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-17T05:13:38Z",
      "summary": "0 commit"
    },
    {
      "id": "15190878206",
      "type": "WatchEvent",
      "repo": "jqssun/android-titanium-browser",
      "repoUrl": "https://api.github.com/repos/jqssun/android-titanium-browser",
      "createdAt": "2026-09-17T03:20:55Z",
      "summary": "dipantau (watch)"
    },
    {
      "id": "21349140974",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-16T19:23:52Z",
      "summary": "0 commit"
    },
    {
      "id": "21348421779",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-16T19:11:58Z",
      "summary": "0 commit"
    },
    {
      "id": "21346225778",
      "type": "PushEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-15T17:27:16Z",
      "summary": "0 commit"
    },
    {
      "id": "21333074349",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-16T19:12:54Z",
      "summary": "0 commit"
    },
    {
      "id": "21331757507",
      "type": "DeleteEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-16T19:18:03Z",
      "summary": "menghapus v0-uji"
    },
    {
      "id": "21325073409",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-16T15:43:11Z",
      "summary": "0 commit"
    },
    {
      "id": "21324888146",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-16T19:11:57Z",
      "summary": "0 commit"
    },
    {
      "id": "21324858027",
      "type": "PushEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-15T03:43:49Z",
      "summary": "0 commit"
    },
    {
      "id": "21324767888",
      "type": "PushEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-15T03:42:34Z",
      "summary": "0 commit"
    },
    {
      "id": "21323662675",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-16T18:56:26Z",
      "summary": "0 commit"
    },
    {
      "id": "21313746225",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-16T16:46:01Z",
      "summary": "0 commit"
    },
    {
      "id": "21312838599",
      "type": "PushEvent",
      "repo": "Niumination/mata-watchdog-pi",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-watchdog-pi",
      "createdAt": "2026-09-16T16:33:42Z",
      "summary": "0 commit"
    },
    {
      "id": "21308556699",
      "type": "PushEvent",
      "repo": "Niumination/mata-watchdog-pi",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-watchdog-pi",
      "createdAt": "2026-09-16T11:51:52Z",
      "summary": "0 commit"
    },
    {
      "id": "21296519370",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-16T12:13:47Z",
      "summary": "0 commit"
    },
    {
      "id": "21293739803",
      "type": "PushEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-15T03:00:20Z",
      "summary": "0 commit"
    },
    {
      "id": "21293361885",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-16T12:13:29Z",
      "summary": "0 commit"
    },
    {
      "id": "21282946120",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-16T09:03:24Z",
      "summary": "0 commit"
    },
    {
      "id": "21282134811",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-16T09:20:44Z",
      "summary": "0 commit"
    },
    {
      "id": "21279721880",
      "type": "PushEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-16T07:34:20Z",
      "summary": "0 commit"
    },
    {
      "id": "21277878151",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-16T08:42:00Z",
      "summary": "0 commit"
    },
    {
      "id": "21277771928",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-16T08:40:30Z",
      "summary": "0 commit"
    },
    {
      "id": "21277373652",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-16T08:32:17Z",
      "summary": "0 commit"
    },
    {
      "id": "21277248619",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-16T08:33:05Z",
      "summary": "0 commit"
    },
    {
      "id": "21275736699",
      "type": "PushEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-16T04:35:49Z",
      "summary": "0 commit"
    },
    {
      "id": "21269127553",
      "type": "PushEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-16T04:34:00Z",
      "summary": "0 commit"
    },
    {
      "id": "21262947308",
      "type": "PushEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-14T15:08:13Z",
      "summary": "0 commit"
    },
    {
      "id": "21261193222",
      "type": "PushEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-16T04:29:06Z",
      "summary": "0 commit"
    },
    {
      "id": "21260783822",
      "type": "PushEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-16T04:22:15Z",
      "summary": "0 commit"
    },
    {
      "id": "21244442449",
      "type": "DeleteEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-15T18:12:28Z",
      "summary": "menghapus gh-pages"
    },
    {
      "id": "21237309561",
      "type": "CreateEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-15T18:05:31Z",
      "summary": "membuat branch “gh-pages”"
    },
    {
      "id": "21237138945",
      "type": "PushEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-15T16:25:49Z",
      "summary": "0 commit"
    },
    {
      "id": "21232471867",
      "type": "PushEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-14T16:02:13Z",
      "summary": "0 commit"
    },
    {
      "id": "21230374122",
      "type": "DeleteEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-15T18:12:38Z",
      "summary": "menghapus gh-pages"
    },
    {
      "id": "21229764542",
      "type": "PushEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-15T16:02:32Z",
      "summary": "0 commit"
    },
    {
      "id": "21227060656",
      "type": "CreateEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-15T18:12:41Z",
      "summary": "membuat branch “gh-pages”"
    },
    {
      "id": "21226904120",
      "type": "PushEvent",
      "repo": "Niumination/PemdiAcehTengah",
      "repoUrl": "https://api.github.com/repos/Niumination/PemdiAcehTengah",
      "createdAt": "2026-09-15T15:26:18Z",
      "summary": "0 commit"
    },
    {
      "id": "21223442835",
      "type": "PushEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-15T16:46:34Z",
      "summary": "0 commit"
    },
    {
      "id": "21222514808",
      "type": "PushEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-14T14:25:58Z",
      "summary": "0 commit"
    },
    {
      "id": "21221169610",
      "type": "PushEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-15T18:58:00Z",
      "summary": "0 commit"
    },
    {
      "id": "21218485971",
      "type": "PushEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-15T18:19:24Z",
      "summary": "0 commit"
    },
    {
      "id": "21218014215",
      "type": "CreateEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-15T18:12:36Z",
      "summary": "membuat branch “gh-pages”"
    },
    {
      "id": "21216781031",
      "type": "PushEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-15T17:54:59Z",
      "summary": "0 commit"
    },
    {
      "id": "21210461480",
      "type": "PushEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-15T16:24:37Z",
      "summary": "0 commit"
    },
    {
      "id": "21206326392",
      "type": "PushEvent",
      "repo": "Niumination/PemdiAcehTengah",
      "repoUrl": "https://api.github.com/repos/Niumination/PemdiAcehTengah",
      "createdAt": "2026-09-15T15:27:26Z",
      "summary": "0 commit"
    },
    {
      "id": "21200037671",
      "type": "PushEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-15T14:01:34Z",
      "summary": "0 commit"
    },
    {
      "id": "21190797343",
      "type": "PushEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-15T10:54:04Z",
      "summary": "0 commit"
    },
    {
      "id": "21184208301",
      "type": "PushEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-15T10:28:37Z",
      "summary": "0 commit"
    },
    {
      "id": "21159257909",
      "type": "PushEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-13T18:04:50Z",
      "summary": "0 commit"
    },
    {
      "id": "21158895212",
      "type": "PushEvent",
      "repo": "Niumination/PemdiAcehTengah",
      "repoUrl": "https://api.github.com/repos/Niumination/PemdiAcehTengah",
      "createdAt": "2026-09-15T04:37:40Z",
      "summary": "0 commit"
    },
    {
      "id": "21153923776",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-15T03:21:51Z",
      "summary": "0 commit"
    },
    {
      "id": "21153710260",
      "type": "PushEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-15T03:18:31Z",
      "summary": "0 commit"
    },
    {
      "id": "21153574024",
      "type": "PushEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-15T03:16:24Z",
      "summary": "0 commit"
    },
    {
      "id": "21150266015",
      "type": "PushEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-13T15:26:32Z",
      "summary": "0 commit"
    },
    {
      "id": "21148997312",
      "type": "PushEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-15T02:03:14Z",
      "summary": "0 commit"
    },
    {
      "id": "21148754122",
      "type": "CreateEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-13T14:52:30Z",
      "summary": "membuat branch “dev”"
    },
    {
      "id": "21145218450",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-13T17:19:55Z",
      "summary": "0 commit"
    },
    {
      "id": "21142939203",
      "type": "PushEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-13T16:38:57Z",
      "summary": "0 commit"
    },
    {
      "id": "21137933308",
      "type": "PushEvent",
      "repo": "Niumination/ecosystem-config",
      "repoUrl": "https://api.github.com/repos/Niumination/ecosystem-config",
      "createdAt": "2026-09-13T14:57:34Z",
      "summary": "0 commit"
    },
    {
      "id": "21108774631",
      "type": "PushEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-14T15:54:03Z",
      "summary": "0 commit"
    },
    {
      "id": "21108263702",
      "type": "PushEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-14T15:48:19Z",
      "summary": "0 commit"
    },
    {
      "id": "21107510612",
      "type": "PushEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-13T11:27:21Z",
      "summary": "0 commit"
    },
    {
      "id": "21104053797",
      "type": "PushEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-14T15:07:41Z",
      "summary": "0 commit"
    },
    {
      "id": "21100874642",
      "type": "PushEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-14T14:54:32Z",
      "summary": "0 commit"
    },
    {
      "id": "21100216178",
      "type": "PushEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-14T14:36:23Z",
      "summary": "0 commit"
    },
    {
      "id": "21099687665",
      "type": "PushEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-14T14:42:26Z",
      "summary": "0 commit"
    },
    {
      "id": "21092481926",
      "type": "PushEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-12T15:59:30Z",
      "summary": "0 commit"
    },
    {
      "id": "21089225273",
      "type": "PushEvent",
      "repo": "Niumination/Mobile-Harness",
      "repoUrl": "https://api.github.com/repos/Niumination/Mobile-Harness",
      "createdAt": "2026-09-12T15:07:31Z",
      "summary": "0 commit"
    },
    {
      "id": "21086921289",
      "type": "PushEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-12T19:06:29Z",
      "summary": "0 commit"
    },
    {
      "id": "21084350619",
      "type": "PushEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-12T13:43:26Z",
      "summary": "0 commit"
    },
    {
      "id": "21076838158",
      "type": "PushEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-14T10:28:31Z",
      "summary": "0 commit"
    },
    {
      "id": "21076044913",
      "type": "PushEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-12T15:46:11Z",
      "summary": "0 commit"
    },
    {
      "id": "21075379783",
      "type": "PushEvent",
      "repo": "Niumination/Mobile-Harness",
      "repoUrl": "https://api.github.com/repos/Niumination/Mobile-Harness",
      "createdAt": "2026-09-12T15:34:23Z",
      "summary": "0 commit"
    },
    {
      "id": "21072296759",
      "type": "PushEvent",
      "repo": "Niumination/Mobile-Harness",
      "repoUrl": "https://api.github.com/repos/Niumination/Mobile-Harness",
      "createdAt": "2026-09-12T14:41:51Z",
      "summary": "0 commit"
    },
    {
      "id": "21068643381",
      "type": "PushEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-12T13:31:26Z",
      "summary": "0 commit"
    },
    {
      "id": "21066029490",
      "type": "PushEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-12T19:22:39Z",
      "summary": "0 commit"
    },
    {
      "id": "21065480082",
      "type": "PushEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-12T07:01:23Z",
      "summary": "0 commit"
    },
    {
      "id": "21063517179",
      "type": "PushEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-14T07:40:57Z",
      "summary": "0 commit"
    },
    {
      "id": "21063505873",
      "type": "PushEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-14T07:29:41Z",
      "summary": "0 commit"
    },
    {
      "id": "21063032890",
      "type": "PushEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-14T07:34:42Z",
      "summary": "0 commit"
    },
    {
      "id": "21062699791",
      "type": "PushEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-14T07:22:01Z",
      "summary": "0 commit"
    },
    {
      "id": "21062337715",
      "type": "PushEvent",
      "repo": "Niumination/mata-aihackfest-2026",
      "repoUrl": "https://api.github.com/repos/Niumination/mata-aihackfest-2026",
      "createdAt": "2026-09-14T07:25:54Z",
      "summary": "0 commit"
    }
  ],
  "live": false,
  "rateLimited": false,
  "updatedAt": "2026-09-19T13:47:15.145Z",
  "source": "fallback-cache"
};
